// Code generated by internal/genvalidate from openapi/openapi.json; DO NOT EDIT.

package apigw

import "github.com/sacloud/sakumock/core"

// bodySchemas maps "METHOD /path" (the mux pattern registered in the route
// table) to the request-body constraints declared in the OpenAPI spec.
// Entries for spec paths the mock does not serve are inert: the
// core.BodyValidator lookup simply never hits them.
var bodySchemas = map[string]*core.BodySchema{
	"POST /certificates": {
		Type: "object",
		Properties: map[string]*core.BodySchema{
			"createdAt": {
				Type: "string",
			},
			"ecdsa": {
				Type: "object",
				Properties: map[string]*core.BodySchema{
					"cert": {
						Type:    "string",
						Pattern: "^-----BEGIN CERTIFICATE-----\\r?\\n(?:[A-Za-z0-9+/=\\r\\n]+)-----END CERTIFICATE-----\\r?\\n?$",
					},
					"expiredAt": {
						Type: "string",
					},
					"key": {
						Type: "string",
					},
				},
			},
			"id": {
				Type: "string",
			},
			"name": {
				Type:      "string",
				MinLength: core.IntPtr(1),
				MaxLength: core.IntPtr(255),
				Pattern:   "^[\\p{L}\\p{N}._\\-]+$",
			},
			"rsa": {
				Type: "object",
				Properties: map[string]*core.BodySchema{
					"cert": {
						Type:    "string",
						Pattern: "^-----BEGIN CERTIFICATE-----\\r?\\n(?:[A-Za-z0-9+/=\\r\\n]+)-----END CERTIFICATE-----\\r?\\n?$",
					},
					"expiredAt": {
						Type: "string",
					},
					"key": {
						Type: "string",
					},
				},
			},
			"updatedAt": {
				Type: "string",
			},
		},
	},
	"POST /domains": {
		Type:     "object",
		Required: []string{"domainName"},
		Properties: map[string]*core.BodySchema{
			"certificateId": {
				Type: "string",
			},
			"certificateName": {
				Type: "string",
			},
			"createdAt": {
				Type: "string",
			},
			"domainName": {
				Type:    "string",
				Pattern: "^\\s*(([a-z\\d]([a-z\\d-]*[a-z\\d])?)\\.)+([a-z\\d-]{2,})(\\.)?\\s*$",
			},
			"id": {
				Type: "string",
			},
			"updatedAt": {
				Type: "string",
			},
		},
	},
	// NOTE: pattern "^[^\\/\\s\\u3000]+$" at POST /groups.allOf[1].tags[] is not RE2-compatible; skipped
	"POST /groups": {
		Type:     "object",
		Required: []string{"name"},
		Properties: map[string]*core.BodySchema{
			"createdAt": {
				Type: "string",
			},
			"id": {
				Type: "string",
			},
			"name": {
				Type:      "string",
				MinLength: core.IntPtr(1),
				MaxLength: core.IntPtr(255),
				Pattern:   "^[\\p{L}\\p{N}._\\-]+$",
			},
			"tags": {
				Type: "array",
				Items: &core.BodySchema{
					Type:      "string",
					MinLength: core.IntPtr(1),
					MaxLength: core.IntPtr(255),
				},
			},
			"updatedAt": {
				Type: "string",
			},
		},
	},
	"POST /oidc": {
		Type:     "object",
		Required: []string{"authenticationMethods", "clientId", "clientSecret", "issuer", "name"},
		Properties: map[string]*core.BodySchema{
			"authenticationMethods": {
				Type: "array",
				Items: &core.BodySchema{
					Type: "string",
					Enum: []any{"authorizationCodeFlow", "accessToken"},
				},
			},
			"clientId": {
				Type: "string",
			},
			"clientSecret": {
				Type: "string",
			},
			"createdAt": {
				Type: "string",
			},
			"hideCredentials": {
				Type: "boolean",
			},
			"id": {
				Type: "string",
			},
			"issuer": {
				Type: "string",
			},
			"name": {
				Type:      "string",
				MinLength: core.IntPtr(1),
				MaxLength: core.IntPtr(255),
				Pattern:   "^[\\p{L}\\p{N}._\\-]+$",
			},
			"refreshTokenParamName": {
				Type: "string",
			},
			"scopes": {
				Type: "array",
				Items: &core.BodySchema{
					Type: "string",
				},
			},
			"tokenAudiences": {
				Type: "array",
				Items: &core.BodySchema{
					Type: "string",
				},
			},
			"updatedAt": {
				Type: "string",
			},
			"useSession": {
				Type: "boolean",
			},
		},
	},
	// NOTE: pattern "^[^\\/\\s\\u3000]+$" at POST /services.allOf[0].allOf[0].allOf[1].tags[] is not RE2-compatible; skipped
	"POST /services": {
		Type:     "object",
		Required: []string{"host", "name", "protocol", "subscription"},
		Properties: map[string]*core.BodySchema{
			"authentication": {
				Type: "string",
				Enum: []any{"none", "basic", "hmac", "jwt", "oidc"},
			},
			"connectTimeout": {
				Type:    "integer",
				Minimum: core.Float64Ptr(1),
				Maximum: core.Float64Ptr(2147483646),
			},
			"corsConfig": {
				Type: "object",
				Properties: map[string]*core.BodySchema{
					"accessControlAllowHeaders": {
						Type:      "string",
						MaxLength: core.IntPtr(4000),
					},
					"accessControlAllowMethods": {
						Type: "array",
						Items: &core.BodySchema{
							Type: "string",
							Enum: []any{"GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS", "HEAD", "CONNECT", "TRACE"},
						},
					},
					"accessControlAllowOrigins": {
						Type:      "string",
						MaxLength: core.IntPtr(4000),
					},
					"accessControlExposedHeaders": {
						Type:      "string",
						MaxLength: core.IntPtr(4000),
					},
					"credentials": {
						Type: "boolean",
					},
					"maxAge": {
						Type: "integer",
					},
					"preflightContinue": {
						Type: "boolean",
					},
					"privateNetwork": {
						Type: "boolean",
					},
				},
			},
			"createdAt": {
				Type: "string",
			},
			"host": {
				Type:      "string",
				MaxLength: core.IntPtr(253),
				Pattern:   "^((([a-zA-Z\\d][a-zA-Z\\d-]*[a-zA-Z\\d]*\\.)+[a-zA-Z]{2,})|((25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)\\.(25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)\\.(25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)\\.(25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)))$",
			},
			"id": {
				Type: "string",
			},
			"name": {
				Type:      "string",
				MinLength: core.IntPtr(1),
				MaxLength: core.IntPtr(255),
				Pattern:   "^[\\p{L}\\p{N}._\\-]+$",
			},
			"objectStorageConfig": {
				Type:     "object",
				Required: []string{"accessKeyID", "bucketName", "endpoint", "region", "secretAccessKey", "useDocumentIndex"},
				Properties: map[string]*core.BodySchema{
					"accessKeyID": {
						Type: "string",
					},
					"bucketName": {
						Type:    "string",
						Pattern: "^[a-z0-9.\\-]*$",
					},
					"endpoint": {
						Type: "string",
					},
					"folderName": {
						Type:    "string",
						Pattern: "^[a-zA-Z0-9_\\-\\/!.*'()]*$",
					},
					"region": {
						Type: "string",
					},
					"secretAccessKey": {
						Type: "string",
					},
					"useDocumentIndex": {
						Type: "boolean",
					},
				},
			},
			"oidc": {
				Type: "object",
				Properties: map[string]*core.BodySchema{
					"id": {
						Type: "string",
					},
					"name": {
						Type: "string",
					},
				},
			},
			"path": {
				Type:      "string",
				MaxLength: core.IntPtr(255),
				Pattern:   "^\\/[a-zA-Z0-9_\\-\\/!.*'()-]*$",
			},
			"port": {
				Type:    "integer",
				Minimum: core.Float64Ptr(0),
				Maximum: core.Float64Ptr(65535),
			},
			"protocol": {
				Type: "string",
				Enum: []any{"http", "https"},
			},
			"readTimeout": {
				Type:    "integer",
				Minimum: core.Float64Ptr(1),
				Maximum: core.Float64Ptr(2147483646),
			},
			"retries": {
				Type:    "integer",
				Minimum: core.Float64Ptr(0),
				Maximum: core.Float64Ptr(32767),
			},
			"routeHost": {
				Type:      "string",
				MaxLength: core.IntPtr(253),
			},
			"subscription": {
				Type:     "object",
				Required: []string{"id"},
				Properties: map[string]*core.BodySchema{
					"id": {
						Type: "string",
					},
				},
			},
			"tags": {
				Type: "array",
				Items: &core.BodySchema{
					Type:      "string",
					MinLength: core.IntPtr(1),
					MaxLength: core.IntPtr(255),
				},
			},
			"updatedAt": {
				Type: "string",
			},
			"writeTimeout": {
				Type:    "integer",
				Minimum: core.Float64Ptr(1),
				Maximum: core.Float64Ptr(2147483646),
			},
		},
	},
	// NOTE: pattern "^[^\\/\\s\\u3000]+$" at POST /services/{serviceId}/routes.allOf[0].allOf[1].tags[] is not RE2-compatible; skipped
	"POST /services/{serviceId}/routes": {
		Type:     "object",
		Required: []string{"methods", "name", "protocols"},
		Properties: map[string]*core.BodySchema{
			"createdAt": {
				Type: "string",
			},
			"host": {
				Type: "string",
			},
			"hosts": {
				Type: "array",
				Items: &core.BodySchema{
					Type: "string",
				},
			},
			"httpsRedirectStatusCode": {
				Type: "integer",
				Enum: []any{float64(301), float64(302), float64(303), float64(307), float64(308), float64(426)},
			},
			"id": {
				Type: "string",
			},
			"ipRestrictionConfig": {
				Type:     "object",
				Required: []string{"ips", "protocols", "restrictedBy"},
				Properties: map[string]*core.BodySchema{
					"ips": {
						Type: "array",
						Items: &core.BodySchema{
							Type:    "string",
							Pattern: "^(?:25[0-5]|2[0-4]\\d|1\\d{2}|[1-9]?\\d)(?:\\.(?:25[0-5]|2[0-4]\\d|1\\d{2}|[1-9]?\\d)){3}$",
						},
						MinItems: core.IntPtr(1),
					},
					"protocols": {
						Type: "string",
						Enum: []any{"http,https", "http", "https"},
					},
					"restrictedBy": {
						Type: "string",
						Enum: []any{"allowIps", "denyIps"},
					},
				},
			},
			"methods": {
				Type: "array",
				Items: &core.BodySchema{
					Type: "string",
					Enum: []any{"GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS", "HEAD", "CONNECT", "TRACE"},
				},
			},
			"name": {
				Type:      "string",
				MinLength: core.IntPtr(1),
				MaxLength: core.IntPtr(255),
				Pattern:   "^[\\p{L}\\p{N}._\\-]+$",
			},
			"path": {
				Type:      "string",
				MaxLength: core.IntPtr(255),
				Pattern:   "^(\\/|~\\/).*",
			},
			"preserveHost": {
				Type: "boolean",
			},
			"protocols": {
				Type: "string",
				Enum: []any{"http,https", "http", "https"},
			},
			"regexPriority": {
				Type:    "integer",
				Minimum: core.Float64Ptr(0),
				Maximum: core.Float64Ptr(255),
			},
			"requestBuffering": {
				Type: "boolean",
			},
			"responseBuffering": {
				Type: "boolean",
			},
			"serviceId": {
				Type: "string",
			},
			"stripPath": {
				Type: "boolean",
			},
			"tags": {
				Type: "array",
				Items: &core.BodySchema{
					Type:      "string",
					MinLength: core.IntPtr(1),
					MaxLength: core.IntPtr(255),
				},
			},
			"updatedAt": {
				Type: "string",
			},
		},
	},
	"POST /subscriptions": {
		Type:     "object",
		Required: []string{"name", "planId"},
		Properties: map[string]*core.BodySchema{
			"name": {
				Type: "string",
			},
			"planId": {
				Type: "string",
			},
		},
	},
	// NOTE: pattern "^[^\\/\\s\\u3000]+$" at POST /users.allOf[0].allOf[1].groups[].allOf[1].tags[] is not RE2-compatible; skipped
	// NOTE: pattern "^[^\\/\\s\\u3000]+$" at POST /users.allOf[0].allOf[1].tags[] is not RE2-compatible; skipped
	"POST /users": {
		Type:     "object",
		Required: []string{"name"},
		Properties: map[string]*core.BodySchema{
			"createdAt": {
				Type: "string",
			},
			"customID": {
				Type: "string",
			},
			"groups": {
				Type: "array",
				Items: &core.BodySchema{
					Type:     "object",
					Required: []string{"name"},
					Properties: map[string]*core.BodySchema{
						"createdAt": {
							Type: "string",
						},
						"id": {
							Type: "string",
						},
						"name": {
							Type:      "string",
							MinLength: core.IntPtr(1),
							MaxLength: core.IntPtr(255),
							Pattern:   "^[\\p{L}\\p{N}._\\-]+$",
						},
						"tags": {
							Type: "array",
							Items: &core.BodySchema{
								Type:      "string",
								MinLength: core.IntPtr(1),
								MaxLength: core.IntPtr(255),
							},
						},
						"updatedAt": {
							Type: "string",
						},
					},
				},
			},
			"id": {
				Type: "string",
			},
			"ipRestrictionConfig": {
				Type:     "object",
				Required: []string{"ips", "protocols", "restrictedBy"},
				Properties: map[string]*core.BodySchema{
					"ips": {
						Type: "array",
						Items: &core.BodySchema{
							Type:    "string",
							Pattern: "^(?:25[0-5]|2[0-4]\\d|1\\d{2}|[1-9]?\\d)(?:\\.(?:25[0-5]|2[0-4]\\d|1\\d{2}|[1-9]?\\d)){3}$",
						},
						MinItems: core.IntPtr(1),
					},
					"protocols": {
						Type: "string",
						Enum: []any{"http,https", "http", "https"},
					},
					"restrictedBy": {
						Type: "string",
						Enum: []any{"allowIps", "denyIps"},
					},
				},
			},
			"name": {
				Type:      "string",
				MinLength: core.IntPtr(1),
				MaxLength: core.IntPtr(255),
				Pattern:   "^[\\p{L}\\p{N}._\\-]+$",
			},
			"tags": {
				Type: "array",
				Items: &core.BodySchema{
					Type:      "string",
					MinLength: core.IntPtr(1),
					MaxLength: core.IntPtr(255),
				},
			},
			"updatedAt": {
				Type: "string",
			},
		},
	},
	"PUT /certificates/{certificateId}": {
		Type: "object",
		Properties: map[string]*core.BodySchema{
			"createdAt": {
				Type: "string",
			},
			"ecdsa": {
				Type: "object",
				Properties: map[string]*core.BodySchema{
					"cert": {
						Type:    "string",
						Pattern: "^-----BEGIN CERTIFICATE-----\\r?\\n(?:[A-Za-z0-9+/=\\r\\n]+)-----END CERTIFICATE-----\\r?\\n?$",
					},
					"expiredAt": {
						Type: "string",
					},
					"key": {
						Type: "string",
					},
				},
			},
			"id": {
				Type: "string",
			},
			"name": {
				Type:      "string",
				MinLength: core.IntPtr(1),
				MaxLength: core.IntPtr(255),
				Pattern:   "^[\\p{L}\\p{N}._\\-]+$",
			},
			"rsa": {
				Type: "object",
				Properties: map[string]*core.BodySchema{
					"cert": {
						Type:    "string",
						Pattern: "^-----BEGIN CERTIFICATE-----\\r?\\n(?:[A-Za-z0-9+/=\\r\\n]+)-----END CERTIFICATE-----\\r?\\n?$",
					},
					"expiredAt": {
						Type: "string",
					},
					"key": {
						Type: "string",
					},
				},
			},
			"updatedAt": {
				Type: "string",
			},
		},
	},
	"PUT /domains/{domainId}": {
		Type: "object",
		Properties: map[string]*core.BodySchema{
			"certificateId": {
				Type: "string",
			},
		},
	},
	// NOTE: pattern "^[^\\/\\s\\u3000]+$" at PUT /groups/{groupId}.allOf[1].tags[] is not RE2-compatible; skipped
	"PUT /groups/{groupId}": {
		Type:     "object",
		Required: []string{"name"},
		Properties: map[string]*core.BodySchema{
			"createdAt": {
				Type: "string",
			},
			"id": {
				Type: "string",
			},
			"name": {
				Type:      "string",
				MinLength: core.IntPtr(1),
				MaxLength: core.IntPtr(255),
				Pattern:   "^[\\p{L}\\p{N}._\\-]+$",
			},
			"tags": {
				Type: "array",
				Items: &core.BodySchema{
					Type:      "string",
					MinLength: core.IntPtr(1),
					MaxLength: core.IntPtr(255),
				},
			},
			"updatedAt": {
				Type: "string",
			},
		},
	},
	"PUT /oidc/{oidcId}": {
		Type:     "object",
		Required: []string{"authenticationMethods", "clientId", "clientSecret", "issuer", "name"},
		Properties: map[string]*core.BodySchema{
			"authenticationMethods": {
				Type: "array",
				Items: &core.BodySchema{
					Type: "string",
					Enum: []any{"authorizationCodeFlow", "accessToken"},
				},
			},
			"clientId": {
				Type: "string",
			},
			"clientSecret": {
				Type: "string",
			},
			"createdAt": {
				Type: "string",
			},
			"hideCredentials": {
				Type: "boolean",
			},
			"id": {
				Type: "string",
			},
			"issuer": {
				Type: "string",
			},
			"name": {
				Type:      "string",
				MinLength: core.IntPtr(1),
				MaxLength: core.IntPtr(255),
				Pattern:   "^[\\p{L}\\p{N}._\\-]+$",
			},
			"refreshTokenParamName": {
				Type: "string",
			},
			"scopes": {
				Type: "array",
				Items: &core.BodySchema{
					Type: "string",
				},
			},
			"tokenAudiences": {
				Type: "array",
				Items: &core.BodySchema{
					Type: "string",
				},
			},
			"updatedAt": {
				Type: "string",
			},
			"useSession": {
				Type: "boolean",
			},
		},
	},
	// NOTE: pattern "^[^\\/\\s\\u3000]+$" at PUT /services/{serviceId}.allOf[0].allOf[1].tags[] is not RE2-compatible; skipped
	"PUT /services/{serviceId}": {
		Type:     "object",
		Required: []string{"host", "name", "protocol"},
		Properties: map[string]*core.BodySchema{
			"authentication": {
				Type: "string",
				Enum: []any{"none", "basic", "hmac", "jwt", "oidc"},
			},
			"connectTimeout": {
				Type:    "integer",
				Minimum: core.Float64Ptr(1),
				Maximum: core.Float64Ptr(2147483646),
			},
			"corsConfig": {
				Type: "object",
				Properties: map[string]*core.BodySchema{
					"accessControlAllowHeaders": {
						Type:      "string",
						MaxLength: core.IntPtr(4000),
					},
					"accessControlAllowMethods": {
						Type: "array",
						Items: &core.BodySchema{
							Type: "string",
							Enum: []any{"GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS", "HEAD", "CONNECT", "TRACE"},
						},
					},
					"accessControlAllowOrigins": {
						Type:      "string",
						MaxLength: core.IntPtr(4000),
					},
					"accessControlExposedHeaders": {
						Type:      "string",
						MaxLength: core.IntPtr(4000),
					},
					"credentials": {
						Type: "boolean",
					},
					"maxAge": {
						Type: "integer",
					},
					"preflightContinue": {
						Type: "boolean",
					},
					"privateNetwork": {
						Type: "boolean",
					},
				},
			},
			"createdAt": {
				Type: "string",
			},
			"host": {
				Type:      "string",
				MaxLength: core.IntPtr(253),
				Pattern:   "^((([a-zA-Z\\d][a-zA-Z\\d-]*[a-zA-Z\\d]*\\.)+[a-zA-Z]{2,})|((25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)\\.(25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)\\.(25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)\\.(25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)))$",
			},
			"id": {
				Type: "string",
			},
			"name": {
				Type:      "string",
				MinLength: core.IntPtr(1),
				MaxLength: core.IntPtr(255),
				Pattern:   "^[\\p{L}\\p{N}._\\-]+$",
			},
			"objectStorageConfig": {
				Type:     "object",
				Required: []string{"accessKeyID", "bucketName", "endpoint", "region", "secretAccessKey", "useDocumentIndex"},
				Properties: map[string]*core.BodySchema{
					"accessKeyID": {
						Type: "string",
					},
					"bucketName": {
						Type:    "string",
						Pattern: "^[a-z0-9.\\-]*$",
					},
					"endpoint": {
						Type: "string",
					},
					"folderName": {
						Type:    "string",
						Pattern: "^[a-zA-Z0-9_\\-\\/!.*'()]*$",
					},
					"region": {
						Type: "string",
					},
					"secretAccessKey": {
						Type: "string",
					},
					"useDocumentIndex": {
						Type: "boolean",
					},
				},
			},
			"oidc": {
				Type: "object",
				Properties: map[string]*core.BodySchema{
					"id": {
						Type: "string",
					},
					"name": {
						Type: "string",
					},
				},
			},
			"path": {
				Type:      "string",
				MaxLength: core.IntPtr(255),
				Pattern:   "^\\/[a-zA-Z0-9_\\-\\/!.*'()-]*$",
			},
			"port": {
				Type:    "integer",
				Minimum: core.Float64Ptr(0),
				Maximum: core.Float64Ptr(65535),
			},
			"protocol": {
				Type: "string",
				Enum: []any{"http", "https"},
			},
			"readTimeout": {
				Type:    "integer",
				Minimum: core.Float64Ptr(1),
				Maximum: core.Float64Ptr(2147483646),
			},
			"retries": {
				Type:    "integer",
				Minimum: core.Float64Ptr(0),
				Maximum: core.Float64Ptr(32767),
			},
			"routeHost": {
				Type:      "string",
				MaxLength: core.IntPtr(253),
			},
			"tags": {
				Type: "array",
				Items: &core.BodySchema{
					Type:      "string",
					MinLength: core.IntPtr(1),
					MaxLength: core.IntPtr(255),
				},
			},
			"updatedAt": {
				Type: "string",
			},
			"writeTimeout": {
				Type:    "integer",
				Minimum: core.Float64Ptr(1),
				Maximum: core.Float64Ptr(2147483646),
			},
		},
	},
	// NOTE: pattern "^[^\\/\\s\\u3000]+$" at PUT /services/{serviceId}/routes/{routeId}.allOf[0].allOf[1].tags[] is not RE2-compatible; skipped
	"PUT /services/{serviceId}/routes/{routeId}": {
		Type:     "object",
		Required: []string{"methods", "name", "protocols"},
		Properties: map[string]*core.BodySchema{
			"createdAt": {
				Type: "string",
			},
			"host": {
				Type: "string",
			},
			"hosts": {
				Type: "array",
				Items: &core.BodySchema{
					Type: "string",
				},
			},
			"httpsRedirectStatusCode": {
				Type: "integer",
				Enum: []any{float64(301), float64(302), float64(303), float64(307), float64(308), float64(426)},
			},
			"id": {
				Type: "string",
			},
			"ipRestrictionConfig": {
				Type:     "object",
				Required: []string{"ips", "protocols", "restrictedBy"},
				Properties: map[string]*core.BodySchema{
					"ips": {
						Type: "array",
						Items: &core.BodySchema{
							Type:    "string",
							Pattern: "^(?:25[0-5]|2[0-4]\\d|1\\d{2}|[1-9]?\\d)(?:\\.(?:25[0-5]|2[0-4]\\d|1\\d{2}|[1-9]?\\d)){3}$",
						},
						MinItems: core.IntPtr(1),
					},
					"protocols": {
						Type: "string",
						Enum: []any{"http,https", "http", "https"},
					},
					"restrictedBy": {
						Type: "string",
						Enum: []any{"allowIps", "denyIps"},
					},
				},
			},
			"methods": {
				Type: "array",
				Items: &core.BodySchema{
					Type: "string",
					Enum: []any{"GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS", "HEAD", "CONNECT", "TRACE"},
				},
			},
			"name": {
				Type:      "string",
				MinLength: core.IntPtr(1),
				MaxLength: core.IntPtr(255),
				Pattern:   "^[\\p{L}\\p{N}._\\-]+$",
			},
			"path": {
				Type:      "string",
				MaxLength: core.IntPtr(255),
				Pattern:   "^(\\/|~\\/).*",
			},
			"preserveHost": {
				Type: "boolean",
			},
			"protocols": {
				Type: "string",
				Enum: []any{"http,https", "http", "https"},
			},
			"regexPriority": {
				Type:    "integer",
				Minimum: core.Float64Ptr(0),
				Maximum: core.Float64Ptr(255),
			},
			"requestBuffering": {
				Type: "boolean",
			},
			"responseBuffering": {
				Type: "boolean",
			},
			"serviceId": {
				Type: "string",
			},
			"stripPath": {
				Type: "boolean",
			},
			"tags": {
				Type: "array",
				Items: &core.BodySchema{
					Type:      "string",
					MinLength: core.IntPtr(1),
					MaxLength: core.IntPtr(255),
				},
			},
			"updatedAt": {
				Type: "string",
			},
		},
	},
	// NOTE: oneOf at PUT /services/{serviceId}/routes/{routeId}/authorization left permissive
	"PUT /services/{serviceId}/routes/{routeId}/request": {
		Type: "object",
		Properties: map[string]*core.BodySchema{
			"add": {
				Type: "object",
				Properties: map[string]*core.BodySchema{
					"body": {
						Type: "array",
						Items: &core.BodySchema{
							Type: "object",
							Properties: map[string]*core.BodySchema{
								"key": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^([a-zA-Z0-9_~\\-\\\\\\p{L}]+(\\.[a-zA-Z0-9_~\\-\\\\\\p{L}]+)*)$",
								},
								"value": {
									Type: "string",
								},
							},
						},
					},
					"headers": {
						Type: "array",
						Items: &core.BodySchema{
							Type: "object",
							Properties: map[string]*core.BodySchema{
								"key": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^[a-zA-Z0-9-_]+$",
								},
								"value": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^[\\x20-\\x7E]*$",
								},
							},
						},
					},
					"queryParams": {
						Type: "array",
						Items: &core.BodySchema{
							Type: "object",
							Properties: map[string]*core.BodySchema{
								"key": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^[a-zA-Z0-9-_.]+$",
								},
								"value": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^([\\w\\-._~!$&'()*+,;=:%]|%[0-9a-fA-F]{2})*$",
								},
							},
						},
					},
				},
			},
			"allow": {
				Type: "object",
				Properties: map[string]*core.BodySchema{
					"body": {
						Type: "array",
						Items: &core.BodySchema{
							Type:      "string",
							MaxLength: core.IntPtr(255),
							Pattern:   "^([a-zA-Z0-9_~\\-\\\\\\p{L}]+(\\.[a-zA-Z0-9_~\\-\\\\\\p{L}]+)*)$",
						},
					},
				},
			},
			"append": {
				Type: "object",
				Properties: map[string]*core.BodySchema{
					"body": {
						Type: "array",
						Items: &core.BodySchema{
							Type: "object",
							Properties: map[string]*core.BodySchema{
								"key": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^([a-zA-Z0-9_~\\-\\\\\\p{L}]+(\\.[a-zA-Z0-9_~\\-\\\\\\p{L}]+)*)$",
								},
								"value": {
									Type: "string",
								},
							},
						},
					},
					"headers": {
						Type: "array",
						Items: &core.BodySchema{
							Type: "object",
							Properties: map[string]*core.BodySchema{
								"key": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^[a-zA-Z0-9-_]+$",
								},
								"value": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^[\\x20-\\x7E]*$",
								},
							},
						},
					},
					"queryParams": {
						Type: "array",
						Items: &core.BodySchema{
							Type: "object",
							Properties: map[string]*core.BodySchema{
								"key": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^[a-zA-Z0-9-_.]+$",
								},
								"value": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^([\\w\\-._~!$&'()*+,;=:%]|%[0-9a-fA-F]{2})*$",
								},
							},
						},
					},
				},
			},
			"httpMethod": {
				Type: "string",
				Enum: []any{"GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS", "HEAD", "CONNECT", "TRACE"},
			},
			"remove": {
				Type: "object",
				Properties: map[string]*core.BodySchema{
					"body": {
						Type: "array",
						Items: &core.BodySchema{
							Type:      "string",
							MaxLength: core.IntPtr(255),
							Pattern:   "^([a-zA-Z0-9_~\\-\\\\\\p{L}]+(\\.[a-zA-Z0-9_~\\-\\\\\\p{L}]+)*)$",
						},
					},
					"headerKeys": {
						Type: "array",
						Items: &core.BodySchema{
							Type:      "string",
							MaxLength: core.IntPtr(255),
							Pattern:   "^[a-zA-Z0-9-_]+$",
						},
					},
					"queryParams": {
						Type: "array",
						Items: &core.BodySchema{
							Type:      "string",
							MaxLength: core.IntPtr(255),
							Pattern:   "^[a-zA-Z0-9-_.]+$",
						},
					},
				},
			},
			"rename": {
				Type: "object",
				Properties: map[string]*core.BodySchema{
					"body": {
						Type: "array",
						Items: &core.BodySchema{
							Type: "object",
							Properties: map[string]*core.BodySchema{
								"from": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^([a-zA-Z0-9_~\\-\\\\\\p{L}]+(\\.[a-zA-Z0-9_~\\-\\\\\\p{L}]+)*)$",
								},
								"to": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^([a-zA-Z0-9_~\\-\\\\\\p{L}]+(\\.[a-zA-Z0-9_~\\-\\\\\\p{L}]+)*)$",
								},
							},
						},
					},
					"headers": {
						Type: "array",
						Items: &core.BodySchema{
							Type: "object",
							Properties: map[string]*core.BodySchema{
								"from": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^[a-zA-Z0-9-_]+$",
								},
								"to": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^[a-zA-Z0-9-_]+$",
								},
							},
						},
					},
					"queryParams": {
						Type: "array",
						Items: &core.BodySchema{
							Type: "object",
							Properties: map[string]*core.BodySchema{
								"from": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^[a-zA-Z0-9-_.]+$",
								},
								"to": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^[a-zA-Z0-9-_.]+$",
								},
							},
						},
					},
				},
			},
			"replace": {
				Type: "object",
				Properties: map[string]*core.BodySchema{
					"body": {
						Type: "array",
						Items: &core.BodySchema{
							Type: "object",
							Properties: map[string]*core.BodySchema{
								"key": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^([a-zA-Z0-9_~\\-\\\\\\p{L}]+(\\.[a-zA-Z0-9_~\\-\\\\\\p{L}]+)*)$",
								},
								"value": {
									Type: "string",
								},
							},
						},
					},
					"headers": {
						Type: "array",
						Items: &core.BodySchema{
							Type: "object",
							Properties: map[string]*core.BodySchema{
								"key": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^[a-zA-Z0-9-_]+$",
								},
								"value": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^[\\x20-\\x7E]*$",
								},
							},
						},
					},
					"queryParams": {
						Type: "array",
						Items: &core.BodySchema{
							Type: "object",
							Properties: map[string]*core.BodySchema{
								"key": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^[a-zA-Z0-9-_.]+$",
								},
								"value": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^([\\w\\-._~!$&'()*+,;=:%]|%[0-9a-fA-F]{2})*$",
								},
							},
						},
					},
				},
			},
		},
	},
	"PUT /services/{serviceId}/routes/{routeId}/response": {
		Type: "object",
		Properties: map[string]*core.BodySchema{
			"add": {
				Type: "object",
				Properties: map[string]*core.BodySchema{
					"headers": {
						Type: "array",
						Items: &core.BodySchema{
							Type: "object",
							Properties: map[string]*core.BodySchema{
								"key": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^[a-zA-Z0-9-]+$",
								},
								"value": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^[\\x20-\\x7E]*$",
								},
							},
						},
					},
					"ifStatusCode": {
						Type: "array",
						Items: &core.BodySchema{
							Type:    "integer",
							Minimum: core.Float64Ptr(100),
							Maximum: core.Float64Ptr(999),
						},
					},
					"json": {
						Type: "array",
						Items: &core.BodySchema{
							Type: "object",
							Properties: map[string]*core.BodySchema{
								"key": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^([a-zA-Z0-9_~\\-\\\\\\p{L}]+(\\.[a-zA-Z0-9_~\\-\\\\\\p{L}]+)*)$",
								},
								"value": {
									Type: "string",
								},
							},
						},
					},
				},
			},
			"allow": {
				Type: "object",
				Properties: map[string]*core.BodySchema{
					"jsonKeys": {
						Type: "array",
						Items: &core.BodySchema{
							Type:      "string",
							MaxLength: core.IntPtr(255),
							Pattern:   "^([a-zA-Z0-9_~\\-\\\\\\p{L}]+(\\.[a-zA-Z0-9_~\\-\\\\\\p{L}]+)*)$",
						},
					},
				},
			},
			"append": {
				Type: "object",
				Properties: map[string]*core.BodySchema{
					"headers": {
						Type: "array",
						Items: &core.BodySchema{
							Type: "object",
							Properties: map[string]*core.BodySchema{
								"key": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^[a-zA-Z0-9-]+$",
								},
								"value": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^[\\x20-\\x7E]*$",
								},
							},
						},
					},
					"ifStatusCode": {
						Type: "array",
						Items: &core.BodySchema{
							Type:    "integer",
							Minimum: core.Float64Ptr(100),
							Maximum: core.Float64Ptr(999),
						},
					},
					"json": {
						Type: "array",
						Items: &core.BodySchema{
							Type: "object",
							Properties: map[string]*core.BodySchema{
								"key": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^([a-zA-Z0-9_~\\-\\\\\\p{L}]+(\\.[a-zA-Z0-9_~\\-\\\\\\p{L}]+)*)$",
								},
								"value": {
									Type: "string",
								},
							},
						},
					},
				},
			},
			"remove": {
				Type: "object",
				Properties: map[string]*core.BodySchema{
					"headerKeys": {
						Type: "array",
						Items: &core.BodySchema{
							Type:      "string",
							MaxLength: core.IntPtr(255),
							Pattern:   "^[a-zA-Z0-9-]+$",
						},
					},
					"ifStatusCode": {
						Type: "array",
						Items: &core.BodySchema{
							Type:    "integer",
							Minimum: core.Float64Ptr(100),
							Maximum: core.Float64Ptr(999),
						},
					},
					"jsonKeys": {
						Type: "array",
						Items: &core.BodySchema{
							Type:      "string",
							MaxLength: core.IntPtr(255),
							Pattern:   "^([a-zA-Z0-9_~\\-\\\\\\p{L}]+(\\.[a-zA-Z0-9_~\\-\\\\\\p{L}]+)*)$",
						},
					},
				},
			},
			"rename": {
				Type: "object",
				Properties: map[string]*core.BodySchema{
					"headers": {
						Type: "array",
						Items: &core.BodySchema{
							Type: "object",
							Properties: map[string]*core.BodySchema{
								"from": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^[a-zA-Z0-9-]+$",
								},
								"to": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^[a-zA-Z0-9-]+$",
								},
							},
						},
					},
					"ifStatusCode": {
						Type: "array",
						Items: &core.BodySchema{
							Type:    "integer",
							Minimum: core.Float64Ptr(100),
							Maximum: core.Float64Ptr(999),
						},
					},
					"json": {
						Type: "array",
						Items: &core.BodySchema{
							Type: "object",
							Properties: map[string]*core.BodySchema{
								"from": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^([a-zA-Z0-9_~\\-\\\\\\p{L}]+(\\.[a-zA-Z0-9_~\\-\\\\\\p{L}]+)*)$",
								},
								"to": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^([a-zA-Z0-9_~\\-\\\\\\p{L}]+(\\.[a-zA-Z0-9_~\\-\\\\\\p{L}]+)*)$",
								},
							},
						},
					},
				},
			},
			"replace": {
				Type: "object",
				Properties: map[string]*core.BodySchema{
					"body": {
						Type: "string",
					},
					"headers": {
						Type: "array",
						Items: &core.BodySchema{
							Type: "object",
							Properties: map[string]*core.BodySchema{
								"key": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^[a-zA-Z0-9-]+$",
								},
								"value": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^[\\x20-\\x7E]*$",
								},
							},
						},
					},
					"ifStatusCode": {
						Type: "array",
						Items: &core.BodySchema{
							Type:    "integer",
							Minimum: core.Float64Ptr(100),
							Maximum: core.Float64Ptr(999),
						},
					},
					"json": {
						Type: "array",
						Items: &core.BodySchema{
							Type: "object",
							Properties: map[string]*core.BodySchema{
								"key": {
									Type:      "string",
									MaxLength: core.IntPtr(255),
									Pattern:   "^([a-zA-Z0-9_~\\-\\\\\\p{L}]+(\\.[a-zA-Z0-9_~\\-\\\\\\p{L}]+)*)$",
								},
								"value": {
									Type: "string",
								},
							},
						},
					},
				},
			},
		},
	},
	"PUT /subscriptions/{subscriptionId}": {
		Type:     "object",
		Required: []string{"name"},
		Properties: map[string]*core.BodySchema{
			"name": {
				Type: "string",
			},
		},
	},
	// NOTE: pattern "^[^\\/\\s\\u3000]+$" at PUT /users/{userId}.allOf[0].allOf[1].groups[].allOf[1].tags[] is not RE2-compatible; skipped
	// NOTE: pattern "^[^\\/\\s\\u3000]+$" at PUT /users/{userId}.allOf[0].allOf[1].tags[] is not RE2-compatible; skipped
	"PUT /users/{userId}": {
		Type:     "object",
		Required: []string{"name"},
		Properties: map[string]*core.BodySchema{
			"createdAt": {
				Type: "string",
			},
			"customID": {
				Type: "string",
			},
			"groups": {
				Type: "array",
				Items: &core.BodySchema{
					Type:     "object",
					Required: []string{"name"},
					Properties: map[string]*core.BodySchema{
						"createdAt": {
							Type: "string",
						},
						"id": {
							Type: "string",
						},
						"name": {
							Type:      "string",
							MinLength: core.IntPtr(1),
							MaxLength: core.IntPtr(255),
							Pattern:   "^[\\p{L}\\p{N}._\\-]+$",
						},
						"tags": {
							Type: "array",
							Items: &core.BodySchema{
								Type:      "string",
								MinLength: core.IntPtr(1),
								MaxLength: core.IntPtr(255),
							},
						},
						"updatedAt": {
							Type: "string",
						},
					},
				},
			},
			"id": {
				Type: "string",
			},
			"ipRestrictionConfig": {
				Type:     "object",
				Required: []string{"ips", "protocols", "restrictedBy"},
				Properties: map[string]*core.BodySchema{
					"ips": {
						Type: "array",
						Items: &core.BodySchema{
							Type:    "string",
							Pattern: "^(?:25[0-5]|2[0-4]\\d|1\\d{2}|[1-9]?\\d)(?:\\.(?:25[0-5]|2[0-4]\\d|1\\d{2}|[1-9]?\\d)){3}$",
						},
						MinItems: core.IntPtr(1),
					},
					"protocols": {
						Type: "string",
						Enum: []any{"http,https", "http", "https"},
					},
					"restrictedBy": {
						Type: "string",
						Enum: []any{"allowIps", "denyIps"},
					},
				},
			},
			"name": {
				Type:      "string",
				MinLength: core.IntPtr(1),
				MaxLength: core.IntPtr(255),
				Pattern:   "^[\\p{L}\\p{N}._\\-]+$",
			},
			"tags": {
				Type: "array",
				Items: &core.BodySchema{
					Type:      "string",
					MinLength: core.IntPtr(1),
					MaxLength: core.IntPtr(255),
				},
			},
			"updatedAt": {
				Type: "string",
			},
		},
	},
	"PUT /users/{userId}/authentication": {
		Type: "object",
		Properties: map[string]*core.BodySchema{
			"basicAuth": {
				Type:     "object",
				Required: []string{"password", "userName"},
				Properties: map[string]*core.BodySchema{
					"createdAt": {
						Type: "string",
					},
					"id": {
						Type: "string",
					},
					"password": {
						Type: "string",
					},
					"updatedAt": {
						Type: "string",
					},
					"userName": {
						Type: "string",
					},
				},
			},
			"hmacAuth": {
				Type:     "object",
				Required: []string{"secret", "userName"},
				Properties: map[string]*core.BodySchema{
					"createdAt": {
						Type: "string",
					},
					"id": {
						Type: "string",
					},
					"secret": {
						Type: "string",
					},
					"updatedAt": {
						Type: "string",
					},
					"userName": {
						Type: "string",
					},
				},
			},
			"jwt": {
				Type:     "object",
				Required: []string{"algorithm", "key", "secret"},
				Properties: map[string]*core.BodySchema{
					"algorithm": {
						Type: "string",
						Enum: []any{"HS256", "HS384", "HS512"},
					},
					"createdAt": {
						Type: "string",
					},
					"id": {
						Type: "string",
					},
					"key": {
						Type: "string",
					},
					"secret": {
						Type: "string",
					},
					"updatedAt": {
						Type: "string",
					},
				},
			},
		},
	},
	// NOTE: oneOf at PUT /users/{userId}/groups[].allOf[1] left permissive
	"PUT /users/{userId}/groups": {
		Items: &core.BodySchema{
			Type:     "object",
			Required: []string{"isAssigned"},
			Properties: map[string]*core.BodySchema{
				"isAssigned": {
					Type: "boolean",
				},
			},
		},
	},
}
