package main

import (
	"fmt"
	"go/format"
	"io"
	"sort"
	"strconv"
	"strings"

	"github.com/sacloud/sakumock/core"
)

// Generate compiles the request-body schemas of every operation in the given
// specs and renders the generated Go source. Output is deterministic: the
// same specs always produce byte-identical source.
func Generate(specPaths []string, pkg, varName string, mapping *Mapping, warn io.Writer) ([]byte, error) {
	var ops []operation
	seen := map[string]string{}
	for _, path := range specPaths {
		doc, err := loadSpec(path)
		if err != nil {
			return nil, err
		}
		specOps, err := collectOperations(doc, mapping, warn)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		for _, op := range specOps {
			if prev, dup := seen[op.key]; dup {
				return nil, fmt.Errorf("route %q defined in both %s and %s", op.key, prev, path)
			}
			seen[op.key] = path
		}
		ops = append(ops, specOps...)
	}
	sort.Slice(ops, func(i, j int) bool { return ops[i].key < ops[j].key })

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by internal/genvalidate from %s; DO NOT EDIT.\n\n", strings.Join(specPaths, ", "))
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("import \"github.com/sacloud/sakumock/core\"\n\n")
	fmt.Fprintf(&b, "// %s maps \"METHOD /path\" (the mux pattern registered in the route\n", varName)
	b.WriteString("// table) to the request-body constraints declared in the OpenAPI spec.\n")
	b.WriteString("// Entries for spec paths the mock does not serve are inert: the\n")
	b.WriteString("// core.BodyValidator lookup simply never hits them.\n")
	fmt.Fprintf(&b, "var %s = map[string]*core.BodySchema{\n", varName)
	for _, op := range ops {
		for _, note := range op.notes {
			fmt.Fprintf(&b, "\t// NOTE: %s\n", note)
		}
		if op.schema == nil {
			if len(op.notes) == 0 {
				fmt.Fprintf(&b, "\t// %q has no enforceable constraints.\n", op.key)
			}
			continue
		}
		fmt.Fprintf(&b, "\t%q: ", op.key)
		writeSchema(&b, op.schema, 1)
		b.WriteString(",\n")
	}
	b.WriteString("}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("formatting generated source: %w", err)
	}
	return src, nil
}

// writeSchema renders a *core.BodySchema literal (without the leading &type
// name, as used in map/field composite literals) at the given indent depth.
func writeSchema(b *strings.Builder, s *core.BodySchema, depth int) {
	ind := strings.Repeat("\t", depth+1)
	b.WriteString("{\n")
	field := func(name, value string) {
		fmt.Fprintf(b, "%s%s: %s,\n", ind, name, value)
	}
	if s.Type != "" {
		field("Type", strconv.Quote(s.Type))
	}
	if s.Nullable {
		field("Nullable", "true")
	}
	if len(s.Required) > 0 {
		quoted := make([]string, len(s.Required))
		for i, r := range s.Required {
			quoted[i] = strconv.Quote(r)
		}
		field("Required", "[]string{"+strings.Join(quoted, ", ")+"}")
	}
	if len(s.Properties) > 0 {
		names := make([]string, 0, len(s.Properties))
		for name := range s.Properties {
			names = append(names, name)
		}
		sort.Strings(names)
		fmt.Fprintf(b, "%sProperties: map[string]*core.BodySchema{\n", ind)
		for _, name := range names {
			fmt.Fprintf(b, "%s\t%q: ", ind, name)
			writeSchema(b, s.Properties[name], depth+2)
			b.WriteString(",\n")
		}
		fmt.Fprintf(b, "%s},\n", ind)
	}
	if s.Items != nil {
		fmt.Fprintf(b, "%sItems: &core.BodySchema", ind)
		writeSchema(b, s.Items, depth+1)
		b.WriteString(",\n")
	}
	if s.MinItems != nil {
		field("MinItems", fmt.Sprintf("core.IntPtr(%d)", *s.MinItems))
	}
	if s.MaxItems != nil {
		field("MaxItems", fmt.Sprintf("core.IntPtr(%d)", *s.MaxItems))
	}
	if s.MinLength != nil {
		field("MinLength", fmt.Sprintf("core.IntPtr(%d)", *s.MinLength))
	}
	if s.MaxLength != nil {
		field("MaxLength", fmt.Sprintf("core.IntPtr(%d)", *s.MaxLength))
	}
	if s.Pattern != "" {
		field("Pattern", strconv.Quote(s.Pattern))
	}
	if s.Minimum != nil {
		field("Minimum", fmt.Sprintf("core.Float64Ptr(%s)", formatFloat(*s.Minimum)))
	}
	if s.Maximum != nil {
		field("Maximum", fmt.Sprintf("core.Float64Ptr(%s)", formatFloat(*s.Maximum)))
	}
	if s.ExclusiveMinimum {
		field("ExclusiveMinimum", "true")
	}
	if s.ExclusiveMaximum {
		field("ExclusiveMaximum", "true")
	}
	if len(s.Enum) > 0 {
		values := make([]string, len(s.Enum))
		for i, e := range s.Enum {
			values[i] = enumLiteral(e)
		}
		field("Enum", "[]any{"+strings.Join(values, ", ")+"}")
	}
	b.WriteString(strings.Repeat("\t", depth) + "}")
}

// enumLiteral renders an enum value so the generated literal compares equal
// to json.Unmarshal output: numbers are emitted as float64.
func enumLiteral(e any) string {
	switch v := e.(type) {
	case string:
		return strconv.Quote(v)
	case bool:
		return strconv.FormatBool(v)
	case float64:
		return fmt.Sprintf("float64(%s)", formatFloat(v))
	}
	return fmt.Sprintf("%#v", e)
}

func formatFloat(f float64) string {
	return strconv.FormatFloat(f, 'f', -1, 64)
}
