// Code generated by internal/genvalidate from openapi/openapi.json; DO NOT EDIT.

package cloudhsm

import "github.com/sacloud/sakumock/core"

// bodySchemas maps "METHOD /path" (the mux pattern registered in the route
// table) to the request-body constraints declared in the OpenAPI spec.
// Entries for spec paths the mock does not serve are inert: the
// core.BodyValidator lookup simply never hits them.
var bodySchemas = map[string]*core.BodySchema{
	"POST /{zone}/api/cloud/1.1/cloudhsm/cloudhsms": {
		Type:     "object",
		Required: []string{"CloudHSM"},
		Properties: map[string]*core.BodySchema{
			"CloudHSM": {
				Type:     "object",
				Required: []string{"IPv4NetworkAddress", "IPv4PrefixLength", "Name"},
				Properties: map[string]*core.BodySchema{
					"Description": {
						Type: "string",
					},
					"IPv4NetworkAddress": {
						Type:      "string",
						MinLength: new(1),
					},
					"IPv4PrefixLength": {
						Type: "integer",
					},
					"Name": {
						Type:      "string",
						MinLength: new(1),
						MaxLength: new(255),
					},
					"Tags": {
						Type:     "array",
						Nullable: true,
						Items: &core.BodySchema{
							Type:      "string",
							MinLength: new(1),
						},
					},
				},
			},
		},
	},
	"POST /{zone}/api/cloud/1.1/cloudhsm/cloudhsms/{cloudhsm_resource_id}/clients": {
		Type:     "object",
		Required: []string{"Client"},
		Properties: map[string]*core.BodySchema{
			"Client": {
				Type:     "object",
				Required: []string{"Certificate", "Name"},
				Properties: map[string]*core.BodySchema{
					"Certificate": {
						Type:      "string",
						MinLength: new(1),
					},
					"Name": {
						Type:      "string",
						MinLength: new(1),
						MaxLength: new(255),
					},
				},
			},
		},
	},
	"POST /{zone}/api/cloud/1.1/cloudhsm/cloudhsms/{resource_id}/peers": {
		Type:     "object",
		Required: []string{"Peer"},
		Properties: map[string]*core.BodySchema{
			"Peer": {
				Type:     "object",
				Required: []string{"ID", "SecretKey"},
				Properties: map[string]*core.BodySchema{
					"ID": {
						Type:      "string",
						MinLength: new(1),
					},
					"SecretKey": {
						Type:      "string",
						MinLength: new(1),
					},
				},
			},
		},
	},
	"POST /{zone}/api/cloud/1.1/cloudhsm/licenses": {
		Type:     "object",
		Required: []string{"License"},
		Properties: map[string]*core.BodySchema{
			"License": {
				Type:     "object",
				Required: []string{"Name", "ServiceClass"},
				Properties: map[string]*core.BodySchema{
					"Description": {
						Type: "string",
					},
					"Name": {
						Type:      "string",
						MinLength: new(1),
						MaxLength: new(255),
					},
					"ServiceClass": {
						Type: "string",
						Enum: []any{"cloud/cloudhsm/license/l7"},
					},
					"Tags": {
						Type:     "array",
						Nullable: true,
						Items: &core.BodySchema{
							Type:      "string",
							MinLength: new(1),
						},
					},
				},
			},
		},
	},
	"PUT /{zone}/api/cloud/1.1/cloudhsm/cloudhsms/{cloudhsm_resource_id}/clients/{id}": {
		Type:     "object",
		Required: []string{"Client"},
		Properties: map[string]*core.BodySchema{
			"Client": {
				Type:     "object",
				Required: []string{"Name"},
				Properties: map[string]*core.BodySchema{
					"Name": {
						Type:      "string",
						MinLength: new(1),
						MaxLength: new(255),
					},
				},
			},
		},
	},
	"PUT /{zone}/api/cloud/1.1/cloudhsm/cloudhsms/{resource_id}": {
		Type:     "object",
		Required: []string{"CloudHSM"},
		Properties: map[string]*core.BodySchema{
			"CloudHSM": {
				Type:     "object",
				Required: []string{"IPv4NetworkAddress", "IPv4PrefixLength", "Name"},
				Properties: map[string]*core.BodySchema{
					"Description": {
						Type: "string",
					},
					"IPv4NetworkAddress": {
						Type:      "string",
						MinLength: new(1),
					},
					"IPv4PrefixLength": {
						Type: "integer",
					},
					"Name": {
						Type:      "string",
						MinLength: new(1),
						MaxLength: new(255),
					},
					"Tags": {
						Type:     "array",
						Nullable: true,
						Items: &core.BodySchema{
							Type:      "string",
							MinLength: new(1),
						},
					},
				},
			},
		},
	},
	"PUT /{zone}/api/cloud/1.1/cloudhsm/licenses/{resource_id}": {
		Type:     "object",
		Required: []string{"License"},
		Properties: map[string]*core.BodySchema{
			"License": {
				Type:     "object",
				Required: []string{"Name"},
				Properties: map[string]*core.BodySchema{
					"Description": {
						Type: "string",
					},
					"Name": {
						Type:      "string",
						MinLength: new(1),
						MaxLength: new(255),
					},
					"Tags": {
						Type:     "array",
						Nullable: true,
						Items: &core.BodySchema{
							Type:      "string",
							MinLength: new(1),
						},
					},
				},
			},
		},
	},
}

// responseSchemas maps "METHOD /path" to the response constraints the
// OpenAPI spec declares, keyed by status code. A nil schema means the
// status is declared but its body carries no checkable constraints; a
// status absent from a route's map is not declared in the spec at all.
var responseSchemas = map[string]map[int]*core.BodySchema{
	"DELETE /{zone}/api/cloud/1.1/cloudhsm/cloudhsms/{cloudhsm_resource_id}/clients/{id}": {
		204: nil,
	},
	"DELETE /{zone}/api/cloud/1.1/cloudhsm/cloudhsms/{resource_id}": {
		204: nil,
	},
	"DELETE /{zone}/api/cloud/1.1/cloudhsm/cloudhsms/{resource_id}/peers/{peer_id}": {
		204: nil,
	},
	"DELETE /{zone}/api/cloud/1.1/cloudhsm/licenses/{resource_id}": {
		204: nil,
	},
	"GET /{zone}/api/cloud/1.1/cloudhsm/cloudhsms": {
		200: {
			Type:     "object",
			Required: []string{"CloudHSMs", "Count", "From", "Total", "is_ok"},
			Properties: map[string]*core.BodySchema{
				"CloudHSMs": {
					Type: "array",
					Items: &core.BodySchema{
						Type:     "object",
						Required: []string{"Availability", "CreatedAt", "Description", "ID", "IPv4Address", "IPv4NetworkAddress", "IPv4PrefixLength", "InitialData", "LocalRouter", "ModifiedAt", "Name", "ServiceClass", "Tags"},
						Properties: map[string]*core.BodySchema{
							"Availability": {
								Type: "string",
								Enum: []any{"precreate", "available", "discontinued"},
							},
							"CreatedAt": {
								Type: "string",
							},
							"Description": {
								Type: "string",
							},
							"ID": {
								Type: "string",
							},
							"IPv4Address": {
								Type: "string",
							},
							"IPv4NetworkAddress": {
								Type: "string",
							},
							"IPv4PrefixLength": {
								Type: "integer",
							},
							"InitialData": {
								Type:     "object",
								Nullable: true,
								Required: []string{"Certificate", "PartitionID", "PartitionName"},
								Properties: map[string]*core.BodySchema{
									"Certificate": {
										Type: "string",
									},
									"PartitionID": {
										Type: "string",
									},
									"PartitionName": {
										Type: "string",
									},
								},
							},
							"LocalRouter": {
								Type:     "object",
								Nullable: true,
								Properties: map[string]*core.BodySchema{
									"ResourceID": {
										Type: "string",
									},
									"SecretKey": {
										Type: "string",
									},
								},
							},
							"ModifiedAt": {
								Type: "string",
							},
							"Name": {
								Type:      "string",
								MaxLength: new(255),
							},
							"ServiceClass": {
								Type: "string",
								Enum: []any{"cloud/cloudhsm/partition"},
							},
							"Tags": {
								Type:     "array",
								Nullable: true,
								Items: &core.BodySchema{
									Type:      "string",
									MinLength: new(1),
								},
							},
						},
					},
				},
				"Count": {
					Type: "integer",
				},
				"From": {
					Type: "integer",
				},
				"Total": {
					Type: "integer",
				},
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
	"GET /{zone}/api/cloud/1.1/cloudhsm/cloudhsms/{cloudhsm_resource_id}/clients": {
		200: {
			Type:     "object",
			Required: []string{"Clients", "Count", "From", "Total", "is_ok"},
			Properties: map[string]*core.BodySchema{
				"Clients": {
					Type: "array",
					Items: &core.BodySchema{
						Type:     "object",
						Required: []string{"Availability", "Certificate", "CreatedAt", "ID", "ModifiedAt", "Name"},
						Properties: map[string]*core.BodySchema{
							"Availability": {
								Type: "string",
								Enum: []any{"precreate", "available", "discontinued"},
							},
							"Certificate": {
								Type: "string",
							},
							"CreatedAt": {
								Type: "string",
							},
							"ID": {
								Type: "string",
							},
							"ModifiedAt": {
								Type: "string",
							},
							"Name": {
								Type:      "string",
								MaxLength: new(255),
							},
						},
					},
				},
				"Count": {
					Type: "integer",
				},
				"From": {
					Type: "integer",
				},
				"Total": {
					Type: "integer",
				},
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
	"GET /{zone}/api/cloud/1.1/cloudhsm/cloudhsms/{cloudhsm_resource_id}/clients/{id}": {
		200: {
			Type:     "object",
			Required: []string{"Client", "is_ok"},
			Properties: map[string]*core.BodySchema{
				"Client": {
					Type:     "object",
					Required: []string{"Availability", "Certificate", "CreatedAt", "ID", "ModifiedAt", "Name"},
					Properties: map[string]*core.BodySchema{
						"Availability": {
							Type: "string",
							Enum: []any{"precreate", "available", "discontinued"},
						},
						"Certificate": {
							Type: "string",
						},
						"CreatedAt": {
							Type: "string",
						},
						"ID": {
							Type: "string",
						},
						"ModifiedAt": {
							Type: "string",
						},
						"Name": {
							Type:      "string",
							MaxLength: new(255),
						},
					},
				},
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
	"GET /{zone}/api/cloud/1.1/cloudhsm/cloudhsms/{resource_id}": {
		200: {
			Type:     "object",
			Required: []string{"CloudHSM", "is_ok"},
			Properties: map[string]*core.BodySchema{
				"CloudHSM": {
					Type:     "object",
					Required: []string{"Availability", "CreatedAt", "Description", "ID", "IPv4Address", "IPv4NetworkAddress", "IPv4PrefixLength", "InitialData", "LocalRouter", "ModifiedAt", "Name", "ServiceClass", "Tags"},
					Properties: map[string]*core.BodySchema{
						"Availability": {
							Type: "string",
							Enum: []any{"precreate", "available", "discontinued"},
						},
						"CreatedAt": {
							Type: "string",
						},
						"Description": {
							Type: "string",
						},
						"ID": {
							Type: "string",
						},
						"IPv4Address": {
							Type: "string",
						},
						"IPv4NetworkAddress": {
							Type: "string",
						},
						"IPv4PrefixLength": {
							Type: "integer",
						},
						"InitialData": {
							Type:     "object",
							Nullable: true,
							Required: []string{"Certificate", "PartitionID", "PartitionName"},
							Properties: map[string]*core.BodySchema{
								"Certificate": {
									Type: "string",
								},
								"PartitionID": {
									Type: "string",
								},
								"PartitionName": {
									Type: "string",
								},
							},
						},
						"LocalRouter": {
							Type:     "object",
							Nullable: true,
							Properties: map[string]*core.BodySchema{
								"ResourceID": {
									Type: "string",
								},
								"SecretKey": {
									Type: "string",
								},
							},
						},
						"ModifiedAt": {
							Type: "string",
						},
						"Name": {
							Type:      "string",
							MaxLength: new(255),
						},
						"ServiceClass": {
							Type: "string",
							Enum: []any{"cloud/cloudhsm/partition"},
						},
						"Tags": {
							Type:     "array",
							Nullable: true,
							Items: &core.BodySchema{
								Type:      "string",
								MinLength: new(1),
							},
						},
					},
				},
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
	"GET /{zone}/api/cloud/1.1/cloudhsm/cloudhsms/{resource_id}/peers": {
		200: {
			Type:     "object",
			Required: []string{"Peers", "is_ok"},
			Properties: map[string]*core.BodySchema{
				"Peers": {
					Type: "array",
					Items: &core.BodySchema{
						Type:     "object",
						Required: []string{"ID", "SecretKey"},
						Properties: map[string]*core.BodySchema{
							"Description": {
								Type: "string",
							},
							"Enabled": {
								Type: "boolean",
							},
							"ID": {
								Type: "string",
							},
							"SecretKey": {
								Type: "string",
							},
						},
					},
				},
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
	"GET /{zone}/api/cloud/1.1/cloudhsm/licenses": {
		200: {
			Type:     "object",
			Required: []string{"Count", "From", "Licenses", "Total", "is_ok"},
			Properties: map[string]*core.BodySchema{
				"Count": {
					Type: "integer",
				},
				"From": {
					Type: "integer",
				},
				"Licenses": {
					Type: "array",
					Items: &core.BodySchema{
						Type:     "object",
						Required: []string{"CreatedAt", "Description", "ID", "ModifiedAt", "Name", "ServiceClass", "Tags"},
						Properties: map[string]*core.BodySchema{
							"CreatedAt": {
								Type: "string",
							},
							"Description": {
								Type: "string",
							},
							"ID": {
								Type: "string",
							},
							"ModifiedAt": {
								Type: "string",
							},
							"Name": {
								Type:      "string",
								MaxLength: new(255),
							},
							"ServiceClass": {
								Type: "string",
								Enum: []any{"cloud/cloudhsm/license/l7"},
							},
							"Tags": {
								Type:     "array",
								Nullable: true,
								Items: &core.BodySchema{
									Type:      "string",
									MinLength: new(1),
								},
							},
						},
					},
				},
				"Total": {
					Type: "integer",
				},
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
	"GET /{zone}/api/cloud/1.1/cloudhsm/licenses/{license_resource_id}/documents": {
		200: {
			Type:     "object",
			Required: []string{"CloudHSMDocuments", "Count", "From", "Total", "is_ok"},
			Properties: map[string]*core.BodySchema{
				"CloudHSMDocuments": {
					Type: "array",
					Items: &core.BodySchema{
						Type:     "object",
						Required: []string{"CreatedAt", "ID", "ModifiedAt", "Name"},
						Properties: map[string]*core.BodySchema{
							"CreatedAt": {
								Type: "string",
							},
							"ID": {
								Type: "string",
							},
							"ModifiedAt": {
								Type: "string",
							},
							"Name": {
								Type: "string",
							},
						},
					},
				},
				"Count": {
					Type: "integer",
				},
				"From": {
					Type: "integer",
				},
				"Total": {
					Type: "integer",
				},
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
	"GET /{zone}/api/cloud/1.1/cloudhsm/licenses/{resource_id}": {
		200: {
			Type:     "object",
			Required: []string{"License", "is_ok"},
			Properties: map[string]*core.BodySchema{
				"License": {
					Type:     "object",
					Required: []string{"CreatedAt", "Description", "ID", "ModifiedAt", "Name", "ServiceClass", "Tags"},
					Properties: map[string]*core.BodySchema{
						"CreatedAt": {
							Type: "string",
						},
						"Description": {
							Type: "string",
						},
						"ID": {
							Type: "string",
						},
						"ModifiedAt": {
							Type: "string",
						},
						"Name": {
							Type:      "string",
							MaxLength: new(255),
						},
						"ServiceClass": {
							Type: "string",
							Enum: []any{"cloud/cloudhsm/license/l7"},
						},
						"Tags": {
							Type:     "array",
							Nullable: true,
							Items: &core.BodySchema{
								Type:      "string",
								MinLength: new(1),
							},
						},
					},
				},
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
	"POST /{zone}/api/cloud/1.1/cloudhsm/cloudhsms": {
		201: {
			Type:     "object",
			Required: []string{"CloudHSM", "is_ok"},
			Properties: map[string]*core.BodySchema{
				"CloudHSM": {
					Type:     "object",
					Required: []string{"IPv4NetworkAddress", "IPv4PrefixLength", "Name"},
					Properties: map[string]*core.BodySchema{
						"Availability": {
							Type: "string",
							Enum: []any{"precreate", "available", "discontinued"},
						},
						"CreatedAt": {
							Type: "string",
						},
						"Description": {
							Type: "string",
						},
						"ID": {
							Type: "string",
						},
						"IPv4Address": {
							Type: "string",
						},
						"IPv4NetworkAddress": {
							Type: "string",
						},
						"IPv4PrefixLength": {
							Type: "integer",
						},
						"ModifiedAt": {
							Type: "string",
						},
						"Name": {
							Type:      "string",
							MaxLength: new(255),
						},
						"ServiceClass": {
							Type: "string",
							Enum: []any{"cloud/cloudhsm/partition"},
						},
						"Tags": {
							Type:     "array",
							Nullable: true,
							Items: &core.BodySchema{
								Type:      "string",
								MinLength: new(1),
							},
						},
					},
				},
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
	"POST /{zone}/api/cloud/1.1/cloudhsm/cloudhsms/{cloudhsm_resource_id}/clients": {
		201: {
			Type:     "object",
			Required: []string{"Client", "is_ok"},
			Properties: map[string]*core.BodySchema{
				"Client": {
					Type:     "object",
					Required: []string{"Certificate", "Name"},
					Properties: map[string]*core.BodySchema{
						"Availability": {
							Type: "string",
							Enum: []any{"precreate", "available", "discontinued"},
						},
						"Certificate": {
							Type: "string",
						},
						"CreatedAt": {
							Type: "string",
						},
						"ID": {
							Type: "string",
						},
						"ModifiedAt": {
							Type: "string",
						},
						"Name": {
							Type:      "string",
							MaxLength: new(255),
						},
					},
				},
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
	"POST /{zone}/api/cloud/1.1/cloudhsm/cloudhsms/{resource_id}/peers": {
		204: nil,
	},
	"POST /{zone}/api/cloud/1.1/cloudhsm/licenses": {
		201: {
			Type:     "object",
			Required: []string{"License", "is_ok"},
			Properties: map[string]*core.BodySchema{
				"License": {
					Type:     "object",
					Required: []string{"Name", "ServiceClass"},
					Properties: map[string]*core.BodySchema{
						"CreatedAt": {
							Type: "string",
						},
						"Description": {
							Type: "string",
						},
						"ID": {
							Type: "string",
						},
						"ModifiedAt": {
							Type: "string",
						},
						"Name": {
							Type:      "string",
							MaxLength: new(255),
						},
						"ServiceClass": {
							Type: "string",
							Enum: []any{"cloud/cloudhsm/license/l7"},
						},
						"Tags": {
							Type:     "array",
							Nullable: true,
							Items: &core.BodySchema{
								Type:      "string",
								MinLength: new(1),
							},
						},
					},
				},
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
	"POST /{zone}/api/cloud/1.1/cloudhsm/licenses/{license_resource_id}/documents/{id}/download": {
		200: {
			Type:     "object",
			Required: []string{"Document", "is_ok"},
			Properties: map[string]*core.BodySchema{
				"Document": {
					Type:     "object",
					Required: []string{"URL"},
					Properties: map[string]*core.BodySchema{
						"URL": {
							Type: "string",
						},
					},
				},
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
	"PUT /{zone}/api/cloud/1.1/cloudhsm/cloudhsms/{cloudhsm_resource_id}/clients/{id}": {
		200: {
			Type:     "object",
			Required: []string{"Client", "is_ok"},
			Properties: map[string]*core.BodySchema{
				"Client": {
					Type:     "object",
					Required: []string{"Availability", "Certificate", "CreatedAt", "ID", "ModifiedAt", "Name"},
					Properties: map[string]*core.BodySchema{
						"Availability": {
							Type: "string",
							Enum: []any{"precreate", "available", "discontinued"},
						},
						"Certificate": {
							Type: "string",
						},
						"CreatedAt": {
							Type: "string",
						},
						"ID": {
							Type: "string",
						},
						"ModifiedAt": {
							Type: "string",
						},
						"Name": {
							Type:      "string",
							MaxLength: new(255),
						},
					},
				},
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
	"PUT /{zone}/api/cloud/1.1/cloudhsm/cloudhsms/{resource_id}": {
		200: {
			Type:     "object",
			Required: []string{"CloudHSM", "is_ok"},
			Properties: map[string]*core.BodySchema{
				"CloudHSM": {
					Type:     "object",
					Required: []string{"Availability", "CreatedAt", "Description", "ID", "IPv4Address", "IPv4NetworkAddress", "IPv4PrefixLength", "InitialData", "LocalRouter", "ModifiedAt", "Name", "ServiceClass", "Tags"},
					Properties: map[string]*core.BodySchema{
						"Availability": {
							Type: "string",
							Enum: []any{"precreate", "available", "discontinued"},
						},
						"CreatedAt": {
							Type: "string",
						},
						"Description": {
							Type: "string",
						},
						"ID": {
							Type: "string",
						},
						"IPv4Address": {
							Type: "string",
						},
						"IPv4NetworkAddress": {
							Type: "string",
						},
						"IPv4PrefixLength": {
							Type: "integer",
						},
						"InitialData": {
							Type:     "object",
							Nullable: true,
							Required: []string{"Certificate", "PartitionID", "PartitionName"},
							Properties: map[string]*core.BodySchema{
								"Certificate": {
									Type: "string",
								},
								"PartitionID": {
									Type: "string",
								},
								"PartitionName": {
									Type: "string",
								},
							},
						},
						"LocalRouter": {
							Type:     "object",
							Nullable: true,
							Properties: map[string]*core.BodySchema{
								"ResourceID": {
									Type: "string",
								},
								"SecretKey": {
									Type: "string",
								},
							},
						},
						"ModifiedAt": {
							Type: "string",
						},
						"Name": {
							Type:      "string",
							MaxLength: new(255),
						},
						"ServiceClass": {
							Type: "string",
							Enum: []any{"cloud/cloudhsm/partition"},
						},
						"Tags": {
							Type:     "array",
							Nullable: true,
							Items: &core.BodySchema{
								Type:      "string",
								MinLength: new(1),
							},
						},
					},
				},
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
	"PUT /{zone}/api/cloud/1.1/cloudhsm/licenses/{resource_id}": {
		200: {
			Type:     "object",
			Required: []string{"License", "is_ok"},
			Properties: map[string]*core.BodySchema{
				"License": {
					Type:     "object",
					Required: []string{"CreatedAt", "Description", "ID", "ModifiedAt", "Name", "ServiceClass", "Tags"},
					Properties: map[string]*core.BodySchema{
						"CreatedAt": {
							Type: "string",
						},
						"Description": {
							Type: "string",
						},
						"ID": {
							Type: "string",
						},
						"ModifiedAt": {
							Type: "string",
						},
						"Name": {
							Type:      "string",
							MaxLength: new(255),
						},
						"ServiceClass": {
							Type: "string",
							Enum: []any{"cloud/cloudhsm/license/l7"},
						},
						"Tags": {
							Type:     "array",
							Nullable: true,
							Items: &core.BodySchema{
								Type:      "string",
								MinLength: new(1),
							},
						},
					},
				},
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
}
