package core

import (
	"fmt"
	"os"
	"strings"
)

// EnvVar is a single environment variable entry used when emitting a client
// environment file (endpoint overrides and dummy credentials for the SDK /
// Terraform provider to load).
type EnvVar struct {
	Key   string
	Value string
}

// DummyCredentialEnv returns the placeholder credential variables every mock
// accepts. The SAKURA Cloud SDK requires them to be set, but the mock does not
// validate them, so any client reaching a mock endpoint authenticates while a
// request that escapes to the real API fails instead of touching an account.
func DummyCredentialEnv() []EnvVar {
	return []EnvVar{
		{Key: "SAKURA_ACCESS_TOKEN", Value: "dummy"},
		{Key: "SAKURA_ACCESS_TOKEN_SECRET", Value: "dummy"},
	}
}

// LogArgs renders env vars as alternating key/value arguments for slog.
func LogArgs(vars []EnvVar) []any {
	args := make([]any, 0, len(vars)*2)
	for _, v := range vars {
		args = append(args, v.Key, v.Value)
	}
	return args
}

// RenderEnvFile renders vars in dotenv format (KEY=value, one per line) with a
// short header explaining how to load the file. The output is consumable by
// `set -a; source <file>; set +a`, direnv, and docker compose.
func RenderEnvFile(vars []EnvVar) string {
	var b strings.Builder
	b.WriteString("# Generated by sakumock. Load before running your SDK / Terraform client:\n")
	b.WriteString("#   set -a; source <this-file>; set +a\n")
	for _, v := range vars {
		fmt.Fprintf(&b, "%s=%s\n", v.Key, v.Value)
	}
	return b.String()
}

// WriteEnvFile writes vars to path in dotenv format (see RenderEnvFile).
func WriteEnvFile(path string, vars []EnvVar) error {
	return os.WriteFile(path, []byte(RenderEnvFile(vars)), 0o644)
}
