package core

import (
	"fmt"
	"os"
	"strings"
)

// EnvVar is a single environment variable entry used when emitting a client
// environment file (endpoint overrides and dummy credentials for the SDK /
// Terraform provider to load).
type EnvVar struct {
	Key   string
	Value string
}

// ClientEnvExtender is an optional interface a ServiceConfig may implement to
// contribute extra client environment variables beyond the SAKURA_ENDPOINTS_*
// overrides returned by ClientEnv — for example the AWS_* variables an aws-cli /
// aws-sdk client needs to reach a data plane served by an external tool. These
// are emitted verbatim (not subject to the env command's --host URL rewriting),
// so they may carry non-URL values such as credentials.
type ClientEnvExtender interface {
	ExtraClientEnv() []EnvVar
}

// DummyCredentialEnv returns the placeholder credential variables every mock
// accepts. The SAKURA Cloud SDK requires them to be set, but the mock does not
// validate them, so any client reaching a mock endpoint authenticates while a
// request that escapes to the real API fails instead of touching an account.
func DummyCredentialEnv() []EnvVar {
	return []EnvVar{
		{Key: "SAKURA_ACCESS_TOKEN", Value: "dummy"},
		{Key: "SAKURA_ACCESS_TOKEN_SECRET", Value: "dummy"},
	}
}

// WithTLSScheme upgrades the scheme of http:// endpoint values to https:// when
// enabled is true, so the emitted client env matches a TLS-served mock. Values
// that are not http:// URLs (credentials, regions, already-https URLs) pass
// through unchanged. It returns vars as-is when enabled is false.
func WithTLSScheme(vars []EnvVar, enabled bool) []EnvVar {
	if !enabled {
		return vars
	}
	out := make([]EnvVar, len(vars))
	for i, v := range vars {
		if rest, ok := strings.CutPrefix(v.Value, "http://"); ok {
			v.Value = "https://" + rest
		}
		out[i] = v
	}
	return out
}

// LogArgs renders env vars as alternating key/value arguments for slog.
func LogArgs(vars []EnvVar) []any {
	args := make([]any, 0, len(vars)*2)
	for _, v := range vars {
		args = append(args, v.Key, v.Value)
	}
	return args
}

// RenderEnvFile renders vars in dotenv format (KEY=value, one per line) with a
// short header explaining how to load the file. When export is true each line is
// prefixed with `export ` so the file can be sourced directly (handy for direnv
// or a plain shell); otherwise it is plain dotenv, consumable by
// `set -a; source <file>; set +a`, direnv, and docker compose.
func RenderEnvFile(vars []EnvVar, export bool) string {
	var b strings.Builder
	b.WriteString("# Generated by sakumock. Load before running your SDK / Terraform client:\n")
	prefix := ""
	if export {
		b.WriteString("#   source <this-file>\n")
		prefix = "export "
	} else {
		b.WriteString("#   set -a; source <this-file>; set +a\n")
	}
	for _, v := range vars {
		fmt.Fprintf(&b, "%s%s=%s\n", prefix, v.Key, v.Value)
	}
	return b.String()
}

// WriteEnvFile writes vars to path in dotenv format (see RenderEnvFile).
func WriteEnvFile(path string, vars []EnvVar, export bool) error {
	return os.WriteFile(path, []byte(RenderEnvFile(vars, export)), 0o644)
}
