// Code generated by internal/genvalidate from openapi/openapi.json; DO NOT EDIT.

package workflows

import "github.com/sacloud/sakumock/core"

// bodySchemas maps "METHOD /path" (the mux pattern registered in the route
// table) to the request-body constraints declared in the OpenAPI spec.
// Entries for spec paths the mock does not serve are inert: the
// core.BodyValidator lookup simply never hits them.
var bodySchemas = map[string]*core.BodySchema{
	"PATCH /workflows/{id}": {
		Type: "object",
		Properties: map[string]*core.BodySchema{
			"ConcurrencyMode": {
				Type: "string",
				Enum: []any{"parallel", "lock", "queue"},
			},
			"Description": {
				Type:      "string",
				MinLength: core.IntPtr(0),
				MaxLength: core.IntPtr(1024),
			},
			"Logging": {
				Type: "boolean",
			},
			"Name": {
				Type:      "string",
				MinLength: core.IntPtr(1),
				MaxLength: core.IntPtr(64),
				Pattern:   "^[a-zA-Z0-9_\\-ーぁ-んァ-ヶ一-龠]+$",
			},
			"Publish": {
				Type: "boolean",
			},
			"Tags": {
				Type: "array",
				Items: &core.BodySchema{
					Type:     "object",
					Required: []string{"Name"},
					Properties: map[string]*core.BodySchema{
						"Name": {
							Type:      "string",
							MinLength: core.IntPtr(1),
							MaxLength: core.IntPtr(64),
						},
					},
				},
			},
		},
	},
	"POST /subscriptions": {
		Type:     "object",
		Required: []string{"PlanId"},
		Properties: map[string]*core.BodySchema{
			"PlanId": {
				Type:    "integer",
				Minimum: core.Float64Ptr(1),
			},
		},
	},
	// NOTE: oneOf at POST /workflows.ServicePrincipalId left permissive
	"POST /workflows": {
		Type:     "object",
		Required: []string{"Logging", "Name", "Publish", "Runbook"},
		Properties: map[string]*core.BodySchema{
			"ConcurrencyMode": {
				Type: "string",
				Enum: []any{"parallel", "lock", "queue"},
			},
			"Description": {
				Type:      "string",
				MinLength: core.IntPtr(0),
				MaxLength: core.IntPtr(1024),
			},
			"Logging": {
				Type: "boolean",
			},
			"Name": {
				Type:      "string",
				MinLength: core.IntPtr(1),
				MaxLength: core.IntPtr(64),
				Pattern:   "^[a-zA-Z0-9_\\-ーぁ-んァ-ヶ一-龠]+$",
			},
			"Publish": {
				Type: "boolean",
			},
			"RevisionAlias": {
				Type:      "string",
				MinLength: core.IntPtr(0),
				MaxLength: core.IntPtr(64),
				Pattern:   "^[a-zA-Z0-9_\\-ーぁ-んァ-ヶ一-龠]*$",
			},
			"Runbook": {
				Type: "string",
			},
			"Tags": {
				Type: "array",
				Items: &core.BodySchema{
					Type:     "object",
					Required: []string{"Name"},
					Properties: map[string]*core.BodySchema{
						"Name": {
							Type:      "string",
							MinLength: core.IntPtr(1),
							MaxLength: core.IntPtr(64),
						},
					},
				},
			},
		},
	},
	"POST /workflows/{id}/executions": {
		Type: "object",
		Properties: map[string]*core.BodySchema{
			"Args": {
				Type:      "string",
				MinLength: core.IntPtr(1),
				MaxLength: core.IntPtr(65536),
			},
			"Name": {
				Type:      "string",
				MinLength: core.IntPtr(1),
				MaxLength: core.IntPtr(64),
				Pattern:   "^[a-zA-Z0-9_\\-ーぁ-んァ-ヶ一-龠]+$",
			},
			"RevisionAlias": {
				Type:      "string",
				MinLength: core.IntPtr(0),
				MaxLength: core.IntPtr(64),
				Pattern:   "^[a-zA-Z0-9_\\-ーぁ-んァ-ヶ一-龠]*$",
			},
			"RevisionId": {
				Type: "integer",
			},
		},
	},
	"POST /workflows/{id}/revisions": {
		Type:     "object",
		Required: []string{"Runbook"},
		Properties: map[string]*core.BodySchema{
			"RevisionAlias": {
				Type:      "string",
				MinLength: core.IntPtr(0),
				MaxLength: core.IntPtr(64),
				Pattern:   "^[a-zA-Z0-9_\\-ーぁ-んァ-ヶ一-龠]*$",
			},
			"Runbook": {
				Type: "string",
			},
		},
	},
	"PUT /workflows/{id}/revisions/{revisionId}/revision_alias": {
		Type:     "object",
		Required: []string{"RevisionAlias"},
		Properties: map[string]*core.BodySchema{
			"RevisionAlias": {
				Type:      "string",
				MinLength: core.IntPtr(0),
				MaxLength: core.IntPtr(64),
				Pattern:   "^[a-zA-Z0-9_\\-ーぁ-んァ-ヶ一-龠]*$",
			},
		},
	},
}
