// Code generated by internal/genvalidate from openapi/openapi.yaml; DO NOT EDIT.

package simplenotification

import "github.com/sacloud/sakumock/core"

// bodySchemas maps "METHOD /path" (the mux pattern registered in the route
// table) to the request-body constraints declared in the OpenAPI spec.
// Entries for spec paths the mock does not serve are inert: the
// core.BodyValidator lookup simply never hits them.
var bodySchemas = map[string]*core.BodySchema{
	// NOTE: oneOf at POST /commonserviceitem.CommonServiceItem.Settings left permissive
	"POST /commonserviceitem": {
		Type:     "object",
		Required: []string{"CommonServiceItem"},
		Properties: map[string]*core.BodySchema{
			"CommonServiceItem": {
				Type:     "object",
				Required: []string{"Description", "Icon", "Name", "Provider", "ServiceClass", "Settings", "Tags"},
				Properties: map[string]*core.BodySchema{
					"Description": {
						Type: "string",
					},
					"Icon": {
						Type:     "object",
						Nullable: true,
						Required: []string{"ID"},
						Properties: map[string]*core.BodySchema{
							"ID": {
								Type: "string",
							},
							"Name": {
								Type: "string",
							},
							"Scope": {
								Type: "string",
							},
							"URL": {
								Type: "string",
							},
						},
					},
					"Name": {
						Type: "string",
					},
					"Provider": {
						Type:     "object",
						Required: []string{"Class"},
						Properties: map[string]*core.BodySchema{
							"Class": {
								Type: "string",
								Enum: []any{"saknoticedestination", "saknoticegroup", "saknoticerouting"},
							},
							"Name": {
								Type: "string",
							},
							"ServiceClass": {
								Type: "string",
							},
						},
					},
					"ServiceClass": {
						Type: "string",
						Enum: []any{"cloud/saknoticedestination/2", "cloud/saknoticegroup/2", "cloud/saknoticerouting/2"},
					},
					"Tags": {
						Type:     "array",
						Nullable: true,
						Items: &core.BodySchema{
							Type: "string",
						},
					},
				},
			},
		},
	},
	"POST /commonserviceitem/{id}/simplenotification/message": {
		Type:     "object",
		Required: []string{"Message"},
		Properties: map[string]*core.BodySchema{
			"Message": {
				Type:      "string",
				MaxLength: core.IntPtr(2048),
			},
		},
	},
	"PUT /commonserviceitem/simplenotification/routing/reorder": {
		Type:     "object",
		Required: []string{"Orders"},
		Properties: map[string]*core.BodySchema{
			"Orders": {
				Type: "array",
				Items: &core.BodySchema{
					Type:     "object",
					Required: []string{"PriorityRank", "RoutingID"},
					Properties: map[string]*core.BodySchema{
						"PriorityRank": {
							Type:    "integer",
							Minimum: core.Float64Ptr(1),
							Maximum: core.Float64Ptr(100),
						},
						"RoutingID": {
							Type:    "string",
							Pattern: "^[0-9]{1,12}$",
						},
					},
				},
			},
		},
	},
	// NOTE: oneOf at PUT /commonserviceitem/{id}.CommonServiceItem.Settings left permissive
	"PUT /commonserviceitem/{id}": {
		Type:     "object",
		Required: []string{"CommonServiceItem"},
		Properties: map[string]*core.BodySchema{
			"CommonServiceItem": {
				Type:     "object",
				Required: []string{"Description", "Icon", "Name", "Tags"},
				Properties: map[string]*core.BodySchema{
					"Description": {
						Type: "string",
					},
					"Icon": {
						Type:     "object",
						Nullable: true,
						Required: []string{"ID"},
						Properties: map[string]*core.BodySchema{
							"ID": {
								Type: "string",
							},
							"Name": {
								Type: "string",
							},
							"Scope": {
								Type: "string",
							},
							"URL": {
								Type: "string",
							},
						},
					},
					"Name": {
						Type: "string",
					},
					"Tags": {
						Type:     "array",
						Nullable: true,
						Items: &core.BodySchema{
							Type: "string",
						},
					},
				},
			},
		},
	},
}

// responseSchemas maps "METHOD /path" to the response constraints the
// OpenAPI spec declares, keyed by status code. A nil schema means the
// status is declared but its body carries no checkable constraints; a
// status absent from a route's map is not declared in the spec at all.
var responseSchemas = map[string]map[int]*core.BodySchema{
	// NOTE: oneOf at DELETE /commonserviceitem/{id} response 200.CommonServiceItem.Settings left permissive
	"DELETE /commonserviceitem/{id}": {
		200: {
			Type:     "object",
			Required: []string{"CommonServiceItem"},
			Properties: map[string]*core.BodySchema{
				"CommonServiceItem": {
					Type:     "object",
					Required: []string{"CreatedAt", "Description", "ID", "Icon", "ModifiedAt", "Name", "Provider", "Settings", "Tags"},
					Properties: map[string]*core.BodySchema{
						"CreatedAt": {
							Type: "string",
						},
						"Description": {
							Type: "string",
						},
						"ID": {
							Type: "string",
						},
						"Icon": {
							Type:     "object",
							Nullable: true,
							Required: []string{"ID"},
							Properties: map[string]*core.BodySchema{
								"ID": {
									Type: "string",
								},
								"Name": {
									Type: "string",
								},
								"Scope": {
									Type: "string",
								},
								"URL": {
									Type: "string",
								},
							},
						},
						"Index": {
							Type: "integer",
						},
						"ModifiedAt": {
							Type: "string",
						},
						"Name": {
							Type: "string",
						},
						"Provider": {
							Type:     "object",
							Required: []string{"Class"},
							Properties: map[string]*core.BodySchema{
								"Class": {
									Type: "string",
									Enum: []any{"saknoticedestination", "saknoticegroup", "saknoticerouting"},
								},
								"Name": {
									Type: "string",
								},
								"ServiceClass": {
									Type: "string",
								},
							},
						},
						"Tags": {
							Type: "array",
							Items: &core.BodySchema{
								Type: "string",
							},
						},
					},
				},
			},
		},
	},
	// NOTE: oneOf at GET /commonserviceitem response 200.CommonServiceItems[].Settings left permissive
	"GET /commonserviceitem": {
		200: {
			Type:     "object",
			Required: []string{"CommonServiceItems"},
			Properties: map[string]*core.BodySchema{
				"CommonServiceItems": {
					Type: "array",
					Items: &core.BodySchema{
						Type:     "object",
						Required: []string{"CreatedAt", "Description", "ID", "Icon", "ModifiedAt", "Name", "Provider", "Settings", "Tags"},
						Properties: map[string]*core.BodySchema{
							"CreatedAt": {
								Type: "string",
							},
							"Description": {
								Type: "string",
							},
							"ID": {
								Type: "string",
							},
							"Icon": {
								Type:     "object",
								Nullable: true,
								Required: []string{"ID"},
								Properties: map[string]*core.BodySchema{
									"ID": {
										Type: "string",
									},
									"Name": {
										Type: "string",
									},
									"Scope": {
										Type: "string",
									},
									"URL": {
										Type: "string",
									},
								},
							},
							"Index": {
								Type: "integer",
							},
							"ModifiedAt": {
								Type: "string",
							},
							"Name": {
								Type: "string",
							},
							"Provider": {
								Type:     "object",
								Required: []string{"Class"},
								Properties: map[string]*core.BodySchema{
									"Class": {
										Type: "string",
										Enum: []any{"saknoticedestination", "saknoticegroup", "saknoticerouting"},
									},
									"Name": {
										Type: "string",
									},
									"ServiceClass": {
										Type: "string",
									},
								},
							},
							"Tags": {
								Type: "array",
								Items: &core.BodySchema{
									Type: "string",
								},
							},
						},
					},
				},
				"Count": {
					Type: "integer",
				},
				"From": {
					Type: "integer",
				},
				"Total": {
					Type: "integer",
				},
			},
		},
	},
	"GET /commonserviceitem/simplenotification/history": {
		200: {
			Type:     "object",
			Required: []string{"NotificationHistories"},
			Properties: map[string]*core.BodySchema{
				"NotificationHistories": {
					Type: "array",
					Items: &core.BodySchema{
						Type:     "object",
						Required: []string{"message", "received_at", "request_id", "source_id", "statuses"},
						Properties: map[string]*core.BodySchema{
							"message": {
								Type:     "object",
								Required: []string{"body", "color", "color_code", "icon_url", "image_url", "title"},
								Properties: map[string]*core.BodySchema{
									"body": {
										Type: "string",
									},
									"color": {
										Type: "string",
									},
									"color_code": {
										Type: "string",
									},
									"icon_url": {
										Type: "string",
									},
									"image_url": {
										Type: "string",
									},
									"title": {
										Type: "string",
									},
								},
							},
							"received_at": {
								Type: "string",
							},
							"request_id": {
								Type: "string",
							},
							"source_id": {
								Type: "string",
							},
							"statuses": {
								Type: "array",
								Items: &core.BodySchema{
									Type:     "object",
									Required: []string{"created_at", "destination_id", "error_info", "group_id", "id", "notification_request_id", "status", "updated_at"},
									Properties: map[string]*core.BodySchema{
										"created_at": {
											Type: "string",
										},
										"destination_id": {
											Type:    "string",
											Pattern: "^[0-9]{12}$",
										},
										"error_info": {
											Type: "string",
										},
										"group_id": {
											Type:    "string",
											Pattern: "^[0-9]{12}$",
										},
										"id": {
											Type: "string",
										},
										"notification_request_id": {
											Type: "string",
										},
										"status": {
											Type: "integer",
											Enum: []any{float64(0), float64(1), float64(2), float64(3), float64(9)},
										},
										"updated_at": {
											Type: "string",
										},
									},
								},
							},
						},
					},
				},
			},
		},
	},
	"GET /commonserviceitem/simplenotification/history/{request_id}": {
		200: {
			Type:     "object",
			Required: []string{"NotificationHistory"},
			Properties: map[string]*core.BodySchema{
				"NotificationHistory": {
					Type:     "object",
					Required: []string{"message", "received_at", "request_id", "source_id", "statuses"},
					Properties: map[string]*core.BodySchema{
						"message": {
							Type:     "object",
							Required: []string{"body", "color", "color_code", "icon_url", "image_url", "title"},
							Properties: map[string]*core.BodySchema{
								"body": {
									Type: "string",
								},
								"color": {
									Type: "string",
								},
								"color_code": {
									Type: "string",
								},
								"icon_url": {
									Type: "string",
								},
								"image_url": {
									Type: "string",
								},
								"title": {
									Type: "string",
								},
							},
						},
						"received_at": {
							Type: "string",
						},
						"request_id": {
							Type: "string",
						},
						"source_id": {
							Type: "string",
						},
						"statuses": {
							Type: "array",
							Items: &core.BodySchema{
								Type:     "object",
								Required: []string{"created_at", "destination_id", "error_info", "group_id", "id", "notification_request_id", "status", "updated_at"},
								Properties: map[string]*core.BodySchema{
									"created_at": {
										Type: "string",
									},
									"destination_id": {
										Type:    "string",
										Pattern: "^[0-9]{12}$",
									},
									"error_info": {
										Type: "string",
									},
									"group_id": {
										Type:    "string",
										Pattern: "^[0-9]{12}$",
									},
									"id": {
										Type: "string",
									},
									"notification_request_id": {
										Type: "string",
									},
									"status": {
										Type: "integer",
										Enum: []any{float64(0), float64(1), float64(2), float64(3), float64(9)},
									},
									"updated_at": {
										Type: "string",
									},
								},
							},
						},
					},
				},
			},
		},
	},
	"GET /commonserviceitem/simplenotification/sources": {
		200: {
			Type:     "object",
			Required: []string{"Sources"},
			Properties: map[string]*core.BodySchema{
				"Sources": {
					Type: "array",
					Items: &core.BodySchema{
						Type:     "object",
						Required: []string{"id", "name"},
						Properties: map[string]*core.BodySchema{
							"id": {
								Type: "string",
							},
							"name": {
								Type: "string",
							},
						},
					},
				},
			},
		},
	},
	// NOTE: oneOf at GET /commonserviceitem/{id} response 200.CommonServiceItem.Settings left permissive
	"GET /commonserviceitem/{id}": {
		200: {
			Type:     "object",
			Required: []string{"CommonServiceItem"},
			Properties: map[string]*core.BodySchema{
				"CommonServiceItem": {
					Type:     "object",
					Required: []string{"CreatedAt", "Description", "ID", "Icon", "ModifiedAt", "Name", "Provider", "Settings", "Tags"},
					Properties: map[string]*core.BodySchema{
						"CreatedAt": {
							Type: "string",
						},
						"Description": {
							Type: "string",
						},
						"ID": {
							Type: "string",
						},
						"Icon": {
							Type:     "object",
							Nullable: true,
							Required: []string{"ID"},
							Properties: map[string]*core.BodySchema{
								"ID": {
									Type: "string",
								},
								"Name": {
									Type: "string",
								},
								"Scope": {
									Type: "string",
								},
								"URL": {
									Type: "string",
								},
							},
						},
						"Index": {
							Type: "integer",
						},
						"ModifiedAt": {
							Type: "string",
						},
						"Name": {
							Type: "string",
						},
						"Provider": {
							Type:     "object",
							Required: []string{"Class"},
							Properties: map[string]*core.BodySchema{
								"Class": {
									Type: "string",
									Enum: []any{"saknoticedestination", "saknoticegroup", "saknoticerouting"},
								},
								"Name": {
									Type: "string",
								},
								"ServiceClass": {
									Type: "string",
								},
							},
						},
						"Tags": {
							Type: "array",
							Items: &core.BodySchema{
								Type: "string",
							},
						},
					},
				},
			},
		},
	},
	"GET /commonserviceitem/{id}/simplenotification/status": {
		200: {
			Type:     "object",
			Required: []string{"NotificationStatus"},
			Properties: map[string]*core.BodySchema{
				"NotificationStatus": {
					Type:     "object",
					Required: []string{"IsValid", "ModifiedAt"},
					Properties: map[string]*core.BodySchema{
						"IsValid": {
							Type: "boolean",
						},
						"ModifiedAt": {
							Type: "string",
						},
					},
				},
			},
		},
	},
	// NOTE: oneOf at POST /commonserviceitem response 201.CommonServiceItem.Settings left permissive
	"POST /commonserviceitem": {
		201: {
			Type:     "object",
			Required: []string{"CommonServiceItem"},
			Properties: map[string]*core.BodySchema{
				"CommonServiceItem": {
					Type:     "object",
					Required: []string{"CreatedAt", "Description", "ID", "Icon", "ModifiedAt", "Name", "Provider", "Settings", "Tags"},
					Properties: map[string]*core.BodySchema{
						"CreatedAt": {
							Type: "string",
						},
						"Description": {
							Type: "string",
						},
						"ID": {
							Type: "string",
						},
						"Icon": {
							Type:     "object",
							Nullable: true,
							Required: []string{"ID"},
							Properties: map[string]*core.BodySchema{
								"ID": {
									Type: "string",
								},
								"Name": {
									Type: "string",
								},
								"Scope": {
									Type: "string",
								},
								"URL": {
									Type: "string",
								},
							},
						},
						"Index": {
							Type: "integer",
						},
						"ModifiedAt": {
							Type: "string",
						},
						"Name": {
							Type: "string",
						},
						"Provider": {
							Type:     "object",
							Required: []string{"Class"},
							Properties: map[string]*core.BodySchema{
								"Class": {
									Type: "string",
									Enum: []any{"saknoticedestination", "saknoticegroup", "saknoticerouting"},
								},
								"Name": {
									Type: "string",
								},
								"ServiceClass": {
									Type: "string",
								},
							},
						},
						"Tags": {
							Type: "array",
							Items: &core.BodySchema{
								Type: "string",
							},
						},
					},
				},
			},
		},
	},
	"POST /commonserviceitem/{id}/simplenotification/message": {
		202: {
			Type:     "object",
			Required: []string{"is_ok"},
			Properties: map[string]*core.BodySchema{
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
	"PUT /commonserviceitem/simplenotification/routing/reorder": {
		202: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
	// NOTE: oneOf at PUT /commonserviceitem/{id} response 200.CommonServiceItem.Settings left permissive
	"PUT /commonserviceitem/{id}": {
		200: {
			Type:     "object",
			Required: []string{"CommonServiceItem"},
			Properties: map[string]*core.BodySchema{
				"CommonServiceItem": {
					Type:     "object",
					Required: []string{"CreatedAt", "Description", "ID", "Icon", "ModifiedAt", "Name", "Provider", "Settings", "Tags"},
					Properties: map[string]*core.BodySchema{
						"CreatedAt": {
							Type: "string",
						},
						"Description": {
							Type: "string",
						},
						"ID": {
							Type: "string",
						},
						"Icon": {
							Type:     "object",
							Nullable: true,
							Required: []string{"ID"},
							Properties: map[string]*core.BodySchema{
								"ID": {
									Type: "string",
								},
								"Name": {
									Type: "string",
								},
								"Scope": {
									Type: "string",
								},
								"URL": {
									Type: "string",
								},
							},
						},
						"Index": {
							Type: "integer",
						},
						"ModifiedAt": {
							Type: "string",
						},
						"Name": {
							Type: "string",
						},
						"Provider": {
							Type:     "object",
							Required: []string{"Class"},
							Properties: map[string]*core.BodySchema{
								"Class": {
									Type: "string",
									Enum: []any{"saknoticedestination", "saknoticegroup", "saknoticerouting"},
								},
								"Name": {
									Type: "string",
								},
								"ServiceClass": {
									Type: "string",
								},
							},
						},
						"Tags": {
							Type: "array",
							Items: &core.BodySchema{
								Type: "string",
							},
						},
					},
				},
			},
		},
	},
}
