// Code generated by internal/genvalidate from openapi/openapi.json; DO NOT EDIT.

package addon

import "github.com/sacloud/sakumock/core"

// bodySchemas maps "METHOD /path" (the mux pattern registered in the route
// table) to the request-body constraints declared in the OpenAPI spec.
// Entries for spec paths the mock does not serve are inert: the
// core.BodyValidator lookup simply never hits them.
var bodySchemas = map[string]*core.BodySchema{
	"POST /ai": {
		Type:     "object",
		Required: []string{"location", "sku"},
		Properties: map[string]*core.BodySchema{
			"location": {
				Type:      "string",
				MinLength: core.IntPtr(1),
			},
			"sku": {
				Type: "integer",
				Enum: []any{float64(1)},
			},
		},
	},
	"POST /analytics/datalake": {
		Type:     "object",
		Required: []string{"location", "performance", "redundancy"},
		Properties: map[string]*core.BodySchema{
			"accountType": {
				Type:     "string",
				Nullable: true,
			},
			"location": {
				Type:      "string",
				MinLength: core.IntPtr(1),
			},
			"performance": {
				Type: "integer",
				Enum: []any{float64(1), float64(2)},
			},
			"redundancy": {
				Type: "integer",
				Enum: []any{float64(1), float64(2), float64(3), float64(4)},
			},
		},
	},
	"POST /analytics/dwh": {
		Type:     "object",
		Required: []string{"location"},
		Properties: map[string]*core.BodySchema{
			"location": {
				Type:      "string",
				MinLength: core.IntPtr(1),
			},
		},
	},
	"POST /analytics/etl": {
		Type:     "object",
		Required: []string{"location"},
		Properties: map[string]*core.BodySchema{
			"location": {
				Type:      "string",
				MinLength: core.IntPtr(1),
			},
		},
	},
	"POST /analytics/query": {
		Type:     "object",
		Required: []string{"location"},
		Properties: map[string]*core.BodySchema{
			"location": {
				Type:      "string",
				MinLength: core.IntPtr(1),
			},
		},
	},
	"POST /analytics/search": {
		Type:     "object",
		Required: []string{"location", "partitionCount", "replicaCount", "sku"},
		Properties: map[string]*core.BodySchema{
			"location": {
				Type:      "string",
				MinLength: core.IntPtr(1),
			},
			"partitionCount": {
				Type: "integer",
			},
			"replicaCount": {
				Type:    "integer",
				Minimum: core.Float64Ptr(1),
				Maximum: core.Float64Ptr(12),
			},
			"sku": {
				Type: "integer",
				Enum: []any{float64(1), float64(2), float64(3), float64(4), float64(5), float64(6), float64(7), float64(8)},
			},
			"skuString": {
				Type:     "string",
				Nullable: true,
			},
		},
	},
	"POST /analytics/streaming": {
		Type:     "object",
		Required: []string{"location", "unitCount"},
		Properties: map[string]*core.BodySchema{
			"location": {
				Type:      "string",
				MinLength: core.IntPtr(1),
			},
			"unitCount": {
				Type:      "string",
				MinLength: core.IntPtr(1),
			},
		},
	},
	"POST /cdn": {
		Type:     "object",
		Required: []string{"endpoint", "location", "profile"},
		Properties: map[string]*core.BodySchema{
			"endpoint": {
				Type:     "object",
				Required: []string{"route"},
				Properties: map[string]*core.BodySchema{
					"route": {
						Type:     "object",
						Required: []string{"originGroup", "patterns"},
						Properties: map[string]*core.BodySchema{
							"originGroup": {
								Type:     "object",
								Required: []string{"origin"},
								Properties: map[string]*core.BodySchema{
									"origin": {
										Type:     "object",
										Required: []string{"hostHeader", "hostName"},
										Properties: map[string]*core.BodySchema{
											"hostHeader": {
												Type:      "string",
												MinLength: core.IntPtr(1),
												MaxLength: core.IntPtr(100),
											},
											"hostName": {
												Type:      "string",
												MinLength: core.IntPtr(1),
												MaxLength: core.IntPtr(100),
											},
										},
									},
								},
							},
							"patterns": {
								Type: "array",
								Items: &core.BodySchema{
									Type: "string",
								},
							},
						},
					},
				},
			},
			"location": {
				Type:      "string",
				MinLength: core.IntPtr(1),
			},
			"profile": {
				Type:     "object",
				Required: []string{"level"},
				Properties: map[string]*core.BodySchema{
					"level": {
						Type: "integer",
						Enum: []any{float64(1), float64(2)},
					},
					"levelNameOfBicepParameter": {
						Type:     "string",
						Nullable: true,
					},
				},
			},
		},
	},
	"POST /security/ddos": {
		Type:     "object",
		Required: []string{"endpoint", "location", "profile"},
		Properties: map[string]*core.BodySchema{
			"endpoint": {
				Type:     "object",
				Required: []string{"route"},
				Properties: map[string]*core.BodySchema{
					"route": {
						Type:     "object",
						Required: []string{"originGroup", "patterns"},
						Properties: map[string]*core.BodySchema{
							"originGroup": {
								Type:     "object",
								Required: []string{"origin"},
								Properties: map[string]*core.BodySchema{
									"origin": {
										Type:     "object",
										Required: []string{"hostHeader", "hostName"},
										Properties: map[string]*core.BodySchema{
											"hostHeader": {
												Type:      "string",
												MinLength: core.IntPtr(1),
												MaxLength: core.IntPtr(100),
											},
											"hostName": {
												Type:      "string",
												MinLength: core.IntPtr(1),
												MaxLength: core.IntPtr(100),
											},
										},
									},
								},
							},
							"patterns": {
								Type: "array",
								Items: &core.BodySchema{
									Type: "string",
								},
							},
						},
					},
				},
			},
			"location": {
				Type:      "string",
				MinLength: core.IntPtr(1),
			},
			"profile": {
				Type:     "object",
				Required: []string{"level"},
				Properties: map[string]*core.BodySchema{
					"level": {
						Type: "integer",
						Enum: []any{float64(1), float64(2)},
					},
					"levelNameOfBicepParameter": {
						Type:     "string",
						Nullable: true,
					},
				},
			},
		},
	},
	"POST /security/vulnerability": {
		Type:     "object",
		Required: []string{"location", "os"},
		Properties: map[string]*core.BodySchema{
			"location": {
				Type:      "string",
				MinLength: core.IntPtr(1),
			},
			"os": {
				Type: "integer",
				Enum: []any{float64(1), float64(2)},
			},
		},
	},
	"POST /security/waf": {
		Type:     "object",
		Required: []string{"endpoint", "location", "profile"},
		Properties: map[string]*core.BodySchema{
			"endpoint": {
				Type:     "object",
				Required: []string{"route"},
				Properties: map[string]*core.BodySchema{
					"route": {
						Type:     "object",
						Required: []string{"originGroup", "patterns"},
						Properties: map[string]*core.BodySchema{
							"originGroup": {
								Type:     "object",
								Required: []string{"origin"},
								Properties: map[string]*core.BodySchema{
									"origin": {
										Type:     "object",
										Required: []string{"hostHeader", "hostName"},
										Properties: map[string]*core.BodySchema{
											"hostHeader": {
												Type:      "string",
												MinLength: core.IntPtr(1),
												MaxLength: core.IntPtr(100),
											},
											"hostName": {
												Type:      "string",
												MinLength: core.IntPtr(1),
												MaxLength: core.IntPtr(100),
											},
										},
									},
								},
							},
							"patterns": {
								Type: "array",
								Items: &core.BodySchema{
									Type: "string",
								},
							},
						},
					},
				},
			},
			"location": {
				Type:      "string",
				MinLength: core.IntPtr(1),
			},
			"profile": {
				Type:     "object",
				Required: []string{"level"},
				Properties: map[string]*core.BodySchema{
					"level": {
						Type: "integer",
						Enum: []any{float64(1), float64(2)},
					},
					"levelNameOfBicepParameter": {
						Type:     "string",
						Nullable: true,
					},
				},
			},
		},
	},
}

// responseSchemas maps "METHOD /path" to the response constraints the
// OpenAPI spec declares, keyed by status code. A nil schema means the
// status is declared but its body carries no checkable constraints; a
// status absent from a route's map is not declared in the spec at all.
var responseSchemas = map[string]map[int]*core.BodySchema{
	"DELETE /ai/{resourceGroupName}": {
		204: nil,
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	"DELETE /analytics/datalake/{resourceGroupName}": {
		204: nil,
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	"DELETE /analytics/dwh/{resourceGroupName}": {
		204: nil,
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	"DELETE /analytics/etl/{resourceGroupName}": {
		204: nil,
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	"DELETE /analytics/query/{resourceGroupName}": {
		204: nil,
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	"DELETE /analytics/search/{resourceGroupName}": {
		204: nil,
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	"DELETE /analytics/streaming/{resourceGroupName}": {
		204: nil,
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	"DELETE /cdn/{resourceGroupName}": {
		204: nil,
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	"DELETE /security/ddos/{resourceGroupName}": {
		204: nil,
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	"DELETE /security/vulnerability/{resourceGroupName}": {
		204: nil,
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	"DELETE /security/waf/{resourceGroupName}": {
		204: nil,
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	// NOTE: recursive $ref #/components/schemas/ResourceIdentifier at GET /ai response 200.resources[].data.id.parent left permissive
	// NOTE: recursive $ref #/components/schemas/ResourceIdentifier at GET /ai response 200.resources[].id.parent left permissive
	"GET /ai": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"resources": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"data": {
								Type: "object",
								Properties: map[string]*core.BodySchema{
									"id": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"location": {
												Type: "object",
												Properties: map[string]*core.BodySchema{
													"displayName": {
														Type:     "string",
														Nullable: true,
													},
													"name": {
														Type:     "string",
														Nullable: true,
													},
												},
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
											"provider": {
												Type:     "string",
												Nullable: true,
											},
											"resourceGroupName": {
												Type:     "string",
												Nullable: true,
											},
											"resourceType": {
												Type: "object",
												Properties: map[string]*core.BodySchema{
													"namespace": {
														Type:     "string",
														Nullable: true,
													},
													"type": {
														Type:     "string",
														Nullable: true,
													},
												},
											},
											"subscriptionId": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"location": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"displayName": {
												Type:     "string",
												Nullable: true,
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"managedBy": {
										Type:     "string",
										Nullable: true,
									},
									"name": {
										Type:     "string",
										Nullable: true,
									},
									"resourceGroupProvisioningState": {
										Type:     "string",
										Nullable: true,
									},
									"resourceType": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"namespace": {
												Type:     "string",
												Nullable: true,
											},
											"type": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"systemData": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"createdBy": {
												Type:     "string",
												Nullable: true,
											},
											"createdByType": {
												Type: "object",
											},
											"createdOn": {
												Type:     "string",
												Nullable: true,
											},
											"lastModifiedBy": {
												Type:     "string",
												Nullable: true,
											},
											"lastModifiedByType": {
												Type: "object",
											},
											"lastModifiedOn": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"tags": {
										Type:     "object",
										Nullable: true,
									},
								},
							},
							"hasData": {
								Type: "boolean",
							},
							"id": {
								Type: "object",
								Properties: map[string]*core.BodySchema{
									"location": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"displayName": {
												Type:     "string",
												Nullable: true,
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"name": {
										Type:     "string",
										Nullable: true,
									},
									"provider": {
										Type:     "string",
										Nullable: true,
									},
									"resourceGroupName": {
										Type:     "string",
										Nullable: true,
									},
									"resourceType": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"namespace": {
												Type:     "string",
												Nullable: true,
											},
											"type": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"subscriptionId": {
										Type:     "string",
										Nullable: true,
									},
								},
							},
							"url": {
								Type: "string",
							},
						},
					},
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	"GET /ai/status/{resourceGroupName}/{deploymentName}": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"id": {
					Type:     "string",
					Nullable: true,
				},
				"name": {
					Type:     "string",
					Nullable: true,
				},
				"properties": {
					Type: "object",
					Properties: map[string]*core.BodySchema{
						"provisioningState": {
							Type:     "string",
							Nullable: true,
						},
						"timestamp": {
							Type: "string",
						},
					},
				},
				"type": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
	},
	"GET /ai/{resourceGroupName}": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"data": {
					Nullable: true,
				},
				"url": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	// NOTE: recursive $ref #/components/schemas/ResourceIdentifier at GET /analytics/datalake response 200.resources[].data.id.parent left permissive
	// NOTE: recursive $ref #/components/schemas/ResourceIdentifier at GET /analytics/datalake response 200.resources[].id.parent left permissive
	"GET /analytics/datalake": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"resources": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"data": {
								Type: "object",
								Properties: map[string]*core.BodySchema{
									"id": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"location": {
												Type: "object",
												Properties: map[string]*core.BodySchema{
													"displayName": {
														Type:     "string",
														Nullable: true,
													},
													"name": {
														Type:     "string",
														Nullable: true,
													},
												},
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
											"provider": {
												Type:     "string",
												Nullable: true,
											},
											"resourceGroupName": {
												Type:     "string",
												Nullable: true,
											},
											"resourceType": {
												Type: "object",
												Properties: map[string]*core.BodySchema{
													"namespace": {
														Type:     "string",
														Nullable: true,
													},
													"type": {
														Type:     "string",
														Nullable: true,
													},
												},
											},
											"subscriptionId": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"location": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"displayName": {
												Type:     "string",
												Nullable: true,
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"managedBy": {
										Type:     "string",
										Nullable: true,
									},
									"name": {
										Type:     "string",
										Nullable: true,
									},
									"resourceGroupProvisioningState": {
										Type:     "string",
										Nullable: true,
									},
									"resourceType": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"namespace": {
												Type:     "string",
												Nullable: true,
											},
											"type": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"systemData": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"createdBy": {
												Type:     "string",
												Nullable: true,
											},
											"createdByType": {
												Type: "object",
											},
											"createdOn": {
												Type:     "string",
												Nullable: true,
											},
											"lastModifiedBy": {
												Type:     "string",
												Nullable: true,
											},
											"lastModifiedByType": {
												Type: "object",
											},
											"lastModifiedOn": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"tags": {
										Type:     "object",
										Nullable: true,
									},
								},
							},
							"hasData": {
								Type: "boolean",
							},
							"id": {
								Type: "object",
								Properties: map[string]*core.BodySchema{
									"location": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"displayName": {
												Type:     "string",
												Nullable: true,
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"name": {
										Type:     "string",
										Nullable: true,
									},
									"provider": {
										Type:     "string",
										Nullable: true,
									},
									"resourceGroupName": {
										Type:     "string",
										Nullable: true,
									},
									"resourceType": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"namespace": {
												Type:     "string",
												Nullable: true,
											},
											"type": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"subscriptionId": {
										Type:     "string",
										Nullable: true,
									},
								},
							},
							"url": {
								Type: "string",
							},
						},
					},
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	"GET /analytics/datalake/status/{resourceGroupName}/{deploymentName}": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"id": {
					Type:     "string",
					Nullable: true,
				},
				"name": {
					Type:     "string",
					Nullable: true,
				},
				"properties": {
					Type: "object",
					Properties: map[string]*core.BodySchema{
						"provisioningState": {
							Type:     "string",
							Nullable: true,
						},
						"timestamp": {
							Type: "string",
						},
					},
				},
				"type": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
	},
	"GET /analytics/datalake/{resourceGroupName}": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"data": {
					Nullable: true,
				},
				"url": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	// NOTE: recursive $ref #/components/schemas/ResourceIdentifier at GET /analytics/dwh response 200.resources[].data.id.parent left permissive
	// NOTE: recursive $ref #/components/schemas/ResourceIdentifier at GET /analytics/dwh response 200.resources[].id.parent left permissive
	"GET /analytics/dwh": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"resources": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"data": {
								Type: "object",
								Properties: map[string]*core.BodySchema{
									"id": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"location": {
												Type: "object",
												Properties: map[string]*core.BodySchema{
													"displayName": {
														Type:     "string",
														Nullable: true,
													},
													"name": {
														Type:     "string",
														Nullable: true,
													},
												},
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
											"provider": {
												Type:     "string",
												Nullable: true,
											},
											"resourceGroupName": {
												Type:     "string",
												Nullable: true,
											},
											"resourceType": {
												Type: "object",
												Properties: map[string]*core.BodySchema{
													"namespace": {
														Type:     "string",
														Nullable: true,
													},
													"type": {
														Type:     "string",
														Nullable: true,
													},
												},
											},
											"subscriptionId": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"location": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"displayName": {
												Type:     "string",
												Nullable: true,
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"managedBy": {
										Type:     "string",
										Nullable: true,
									},
									"name": {
										Type:     "string",
										Nullable: true,
									},
									"resourceGroupProvisioningState": {
										Type:     "string",
										Nullable: true,
									},
									"resourceType": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"namespace": {
												Type:     "string",
												Nullable: true,
											},
											"type": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"systemData": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"createdBy": {
												Type:     "string",
												Nullable: true,
											},
											"createdByType": {
												Type: "object",
											},
											"createdOn": {
												Type:     "string",
												Nullable: true,
											},
											"lastModifiedBy": {
												Type:     "string",
												Nullable: true,
											},
											"lastModifiedByType": {
												Type: "object",
											},
											"lastModifiedOn": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"tags": {
										Type:     "object",
										Nullable: true,
									},
								},
							},
							"hasData": {
								Type: "boolean",
							},
							"id": {
								Type: "object",
								Properties: map[string]*core.BodySchema{
									"location": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"displayName": {
												Type:     "string",
												Nullable: true,
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"name": {
										Type:     "string",
										Nullable: true,
									},
									"provider": {
										Type:     "string",
										Nullable: true,
									},
									"resourceGroupName": {
										Type:     "string",
										Nullable: true,
									},
									"resourceType": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"namespace": {
												Type:     "string",
												Nullable: true,
											},
											"type": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"subscriptionId": {
										Type:     "string",
										Nullable: true,
									},
								},
							},
							"url": {
								Type: "string",
							},
						},
					},
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	"GET /analytics/dwh/status/{resourceGroupName}/{deploymentName}": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"id": {
					Type:     "string",
					Nullable: true,
				},
				"name": {
					Type:     "string",
					Nullable: true,
				},
				"properties": {
					Type: "object",
					Properties: map[string]*core.BodySchema{
						"provisioningState": {
							Type:     "string",
							Nullable: true,
						},
						"timestamp": {
							Type: "string",
						},
					},
				},
				"type": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
	},
	"GET /analytics/dwh/{resourceGroupName}": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"data": {
					Nullable: true,
				},
				"url": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	// NOTE: recursive $ref #/components/schemas/ResourceIdentifier at GET /analytics/etl response 200.resources[].data.id.parent left permissive
	// NOTE: recursive $ref #/components/schemas/ResourceIdentifier at GET /analytics/etl response 200.resources[].id.parent left permissive
	"GET /analytics/etl": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"resources": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"data": {
								Type: "object",
								Properties: map[string]*core.BodySchema{
									"id": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"location": {
												Type: "object",
												Properties: map[string]*core.BodySchema{
													"displayName": {
														Type:     "string",
														Nullable: true,
													},
													"name": {
														Type:     "string",
														Nullable: true,
													},
												},
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
											"provider": {
												Type:     "string",
												Nullable: true,
											},
											"resourceGroupName": {
												Type:     "string",
												Nullable: true,
											},
											"resourceType": {
												Type: "object",
												Properties: map[string]*core.BodySchema{
													"namespace": {
														Type:     "string",
														Nullable: true,
													},
													"type": {
														Type:     "string",
														Nullable: true,
													},
												},
											},
											"subscriptionId": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"location": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"displayName": {
												Type:     "string",
												Nullable: true,
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"managedBy": {
										Type:     "string",
										Nullable: true,
									},
									"name": {
										Type:     "string",
										Nullable: true,
									},
									"resourceGroupProvisioningState": {
										Type:     "string",
										Nullable: true,
									},
									"resourceType": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"namespace": {
												Type:     "string",
												Nullable: true,
											},
											"type": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"systemData": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"createdBy": {
												Type:     "string",
												Nullable: true,
											},
											"createdByType": {
												Type: "object",
											},
											"createdOn": {
												Type:     "string",
												Nullable: true,
											},
											"lastModifiedBy": {
												Type:     "string",
												Nullable: true,
											},
											"lastModifiedByType": {
												Type: "object",
											},
											"lastModifiedOn": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"tags": {
										Type:     "object",
										Nullable: true,
									},
								},
							},
							"hasData": {
								Type: "boolean",
							},
							"id": {
								Type: "object",
								Properties: map[string]*core.BodySchema{
									"location": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"displayName": {
												Type:     "string",
												Nullable: true,
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"name": {
										Type:     "string",
										Nullable: true,
									},
									"provider": {
										Type:     "string",
										Nullable: true,
									},
									"resourceGroupName": {
										Type:     "string",
										Nullable: true,
									},
									"resourceType": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"namespace": {
												Type:     "string",
												Nullable: true,
											},
											"type": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"subscriptionId": {
										Type:     "string",
										Nullable: true,
									},
								},
							},
							"url": {
								Type: "string",
							},
						},
					},
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	"GET /analytics/etl/status/{resourceGroupName}/{deploymentName}": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"id": {
					Type:     "string",
					Nullable: true,
				},
				"name": {
					Type:     "string",
					Nullable: true,
				},
				"properties": {
					Type: "object",
					Properties: map[string]*core.BodySchema{
						"provisioningState": {
							Type:     "string",
							Nullable: true,
						},
						"timestamp": {
							Type: "string",
						},
					},
				},
				"type": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
	},
	"GET /analytics/etl/{resourceGroupName}": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"data": {
					Nullable: true,
				},
				"url": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	// NOTE: recursive $ref #/components/schemas/ResourceIdentifier at GET /analytics/query response 200.resources[].data.id.parent left permissive
	// NOTE: recursive $ref #/components/schemas/ResourceIdentifier at GET /analytics/query response 200.resources[].id.parent left permissive
	"GET /analytics/query": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"resources": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"data": {
								Type: "object",
								Properties: map[string]*core.BodySchema{
									"id": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"location": {
												Type: "object",
												Properties: map[string]*core.BodySchema{
													"displayName": {
														Type:     "string",
														Nullable: true,
													},
													"name": {
														Type:     "string",
														Nullable: true,
													},
												},
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
											"provider": {
												Type:     "string",
												Nullable: true,
											},
											"resourceGroupName": {
												Type:     "string",
												Nullable: true,
											},
											"resourceType": {
												Type: "object",
												Properties: map[string]*core.BodySchema{
													"namespace": {
														Type:     "string",
														Nullable: true,
													},
													"type": {
														Type:     "string",
														Nullable: true,
													},
												},
											},
											"subscriptionId": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"location": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"displayName": {
												Type:     "string",
												Nullable: true,
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"managedBy": {
										Type:     "string",
										Nullable: true,
									},
									"name": {
										Type:     "string",
										Nullable: true,
									},
									"resourceGroupProvisioningState": {
										Type:     "string",
										Nullable: true,
									},
									"resourceType": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"namespace": {
												Type:     "string",
												Nullable: true,
											},
											"type": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"systemData": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"createdBy": {
												Type:     "string",
												Nullable: true,
											},
											"createdByType": {
												Type: "object",
											},
											"createdOn": {
												Type:     "string",
												Nullable: true,
											},
											"lastModifiedBy": {
												Type:     "string",
												Nullable: true,
											},
											"lastModifiedByType": {
												Type: "object",
											},
											"lastModifiedOn": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"tags": {
										Type:     "object",
										Nullable: true,
									},
								},
							},
							"hasData": {
								Type: "boolean",
							},
							"id": {
								Type: "object",
								Properties: map[string]*core.BodySchema{
									"location": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"displayName": {
												Type:     "string",
												Nullable: true,
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"name": {
										Type:     "string",
										Nullable: true,
									},
									"provider": {
										Type:     "string",
										Nullable: true,
									},
									"resourceGroupName": {
										Type:     "string",
										Nullable: true,
									},
									"resourceType": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"namespace": {
												Type:     "string",
												Nullable: true,
											},
											"type": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"subscriptionId": {
										Type:     "string",
										Nullable: true,
									},
								},
							},
							"url": {
								Type: "string",
							},
						},
					},
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	"GET /analytics/query/status/{resourceGroupName}/{deploymentName}": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"id": {
					Type:     "string",
					Nullable: true,
				},
				"name": {
					Type:     "string",
					Nullable: true,
				},
				"properties": {
					Type: "object",
					Properties: map[string]*core.BodySchema{
						"provisioningState": {
							Type:     "string",
							Nullable: true,
						},
						"timestamp": {
							Type: "string",
						},
					},
				},
				"type": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
	},
	"GET /analytics/query/{resourceGroupName}": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"data": {
					Nullable: true,
				},
				"url": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	// NOTE: recursive $ref #/components/schemas/ResourceIdentifier at GET /analytics/search response 200.resources[].data.id.parent left permissive
	// NOTE: recursive $ref #/components/schemas/ResourceIdentifier at GET /analytics/search response 200.resources[].id.parent left permissive
	"GET /analytics/search": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"resources": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"data": {
								Type: "object",
								Properties: map[string]*core.BodySchema{
									"id": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"location": {
												Type: "object",
												Properties: map[string]*core.BodySchema{
													"displayName": {
														Type:     "string",
														Nullable: true,
													},
													"name": {
														Type:     "string",
														Nullable: true,
													},
												},
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
											"provider": {
												Type:     "string",
												Nullable: true,
											},
											"resourceGroupName": {
												Type:     "string",
												Nullable: true,
											},
											"resourceType": {
												Type: "object",
												Properties: map[string]*core.BodySchema{
													"namespace": {
														Type:     "string",
														Nullable: true,
													},
													"type": {
														Type:     "string",
														Nullable: true,
													},
												},
											},
											"subscriptionId": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"location": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"displayName": {
												Type:     "string",
												Nullable: true,
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"managedBy": {
										Type:     "string",
										Nullable: true,
									},
									"name": {
										Type:     "string",
										Nullable: true,
									},
									"resourceGroupProvisioningState": {
										Type:     "string",
										Nullable: true,
									},
									"resourceType": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"namespace": {
												Type:     "string",
												Nullable: true,
											},
											"type": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"systemData": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"createdBy": {
												Type:     "string",
												Nullable: true,
											},
											"createdByType": {
												Type: "object",
											},
											"createdOn": {
												Type:     "string",
												Nullable: true,
											},
											"lastModifiedBy": {
												Type:     "string",
												Nullable: true,
											},
											"lastModifiedByType": {
												Type: "object",
											},
											"lastModifiedOn": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"tags": {
										Type:     "object",
										Nullable: true,
									},
								},
							},
							"hasData": {
								Type: "boolean",
							},
							"id": {
								Type: "object",
								Properties: map[string]*core.BodySchema{
									"location": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"displayName": {
												Type:     "string",
												Nullable: true,
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"name": {
										Type:     "string",
										Nullable: true,
									},
									"provider": {
										Type:     "string",
										Nullable: true,
									},
									"resourceGroupName": {
										Type:     "string",
										Nullable: true,
									},
									"resourceType": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"namespace": {
												Type:     "string",
												Nullable: true,
											},
											"type": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"subscriptionId": {
										Type:     "string",
										Nullable: true,
									},
								},
							},
							"url": {
								Type: "string",
							},
						},
					},
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	"GET /analytics/search/status/{resourceGroupName}/{deploymentName}": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"id": {
					Type:     "string",
					Nullable: true,
				},
				"name": {
					Type:     "string",
					Nullable: true,
				},
				"properties": {
					Type: "object",
					Properties: map[string]*core.BodySchema{
						"provisioningState": {
							Type:     "string",
							Nullable: true,
						},
						"timestamp": {
							Type: "string",
						},
					},
				},
				"type": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
	},
	"GET /analytics/search/{resourceGroupName}": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"data": {
					Nullable: true,
				},
				"url": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	// NOTE: recursive $ref #/components/schemas/ResourceIdentifier at GET /analytics/streaming response 200.resources[].data.id.parent left permissive
	// NOTE: recursive $ref #/components/schemas/ResourceIdentifier at GET /analytics/streaming response 200.resources[].id.parent left permissive
	"GET /analytics/streaming": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"resources": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"data": {
								Type: "object",
								Properties: map[string]*core.BodySchema{
									"id": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"location": {
												Type: "object",
												Properties: map[string]*core.BodySchema{
													"displayName": {
														Type:     "string",
														Nullable: true,
													},
													"name": {
														Type:     "string",
														Nullable: true,
													},
												},
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
											"provider": {
												Type:     "string",
												Nullable: true,
											},
											"resourceGroupName": {
												Type:     "string",
												Nullable: true,
											},
											"resourceType": {
												Type: "object",
												Properties: map[string]*core.BodySchema{
													"namespace": {
														Type:     "string",
														Nullable: true,
													},
													"type": {
														Type:     "string",
														Nullable: true,
													},
												},
											},
											"subscriptionId": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"location": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"displayName": {
												Type:     "string",
												Nullable: true,
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"managedBy": {
										Type:     "string",
										Nullable: true,
									},
									"name": {
										Type:     "string",
										Nullable: true,
									},
									"resourceGroupProvisioningState": {
										Type:     "string",
										Nullable: true,
									},
									"resourceType": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"namespace": {
												Type:     "string",
												Nullable: true,
											},
											"type": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"systemData": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"createdBy": {
												Type:     "string",
												Nullable: true,
											},
											"createdByType": {
												Type: "object",
											},
											"createdOn": {
												Type:     "string",
												Nullable: true,
											},
											"lastModifiedBy": {
												Type:     "string",
												Nullable: true,
											},
											"lastModifiedByType": {
												Type: "object",
											},
											"lastModifiedOn": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"tags": {
										Type:     "object",
										Nullable: true,
									},
								},
							},
							"hasData": {
								Type: "boolean",
							},
							"id": {
								Type: "object",
								Properties: map[string]*core.BodySchema{
									"location": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"displayName": {
												Type:     "string",
												Nullable: true,
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"name": {
										Type:     "string",
										Nullable: true,
									},
									"provider": {
										Type:     "string",
										Nullable: true,
									},
									"resourceGroupName": {
										Type:     "string",
										Nullable: true,
									},
									"resourceType": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"namespace": {
												Type:     "string",
												Nullable: true,
											},
											"type": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"subscriptionId": {
										Type:     "string",
										Nullable: true,
									},
								},
							},
							"url": {
								Type: "string",
							},
						},
					},
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	"GET /analytics/streaming/status/{resourceGroupName}/{deploymentName}": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"id": {
					Type:     "string",
					Nullable: true,
				},
				"name": {
					Type:     "string",
					Nullable: true,
				},
				"properties": {
					Type: "object",
					Properties: map[string]*core.BodySchema{
						"provisioningState": {
							Type:     "string",
							Nullable: true,
						},
						"timestamp": {
							Type: "string",
						},
					},
				},
				"type": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
	},
	"GET /analytics/streaming/{resourceGroupName}": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"data": {
					Nullable: true,
				},
				"url": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	// NOTE: recursive $ref #/components/schemas/ResourceIdentifier at GET /cdn response 200.resources[].data.id.parent left permissive
	// NOTE: recursive $ref #/components/schemas/ResourceIdentifier at GET /cdn response 200.resources[].id.parent left permissive
	"GET /cdn": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"resources": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"data": {
								Type: "object",
								Properties: map[string]*core.BodySchema{
									"id": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"location": {
												Type: "object",
												Properties: map[string]*core.BodySchema{
													"displayName": {
														Type:     "string",
														Nullable: true,
													},
													"name": {
														Type:     "string",
														Nullable: true,
													},
												},
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
											"provider": {
												Type:     "string",
												Nullable: true,
											},
											"resourceGroupName": {
												Type:     "string",
												Nullable: true,
											},
											"resourceType": {
												Type: "object",
												Properties: map[string]*core.BodySchema{
													"namespace": {
														Type:     "string",
														Nullable: true,
													},
													"type": {
														Type:     "string",
														Nullable: true,
													},
												},
											},
											"subscriptionId": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"location": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"displayName": {
												Type:     "string",
												Nullable: true,
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"managedBy": {
										Type:     "string",
										Nullable: true,
									},
									"name": {
										Type:     "string",
										Nullable: true,
									},
									"resourceGroupProvisioningState": {
										Type:     "string",
										Nullable: true,
									},
									"resourceType": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"namespace": {
												Type:     "string",
												Nullable: true,
											},
											"type": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"systemData": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"createdBy": {
												Type:     "string",
												Nullable: true,
											},
											"createdByType": {
												Type: "object",
											},
											"createdOn": {
												Type:     "string",
												Nullable: true,
											},
											"lastModifiedBy": {
												Type:     "string",
												Nullable: true,
											},
											"lastModifiedByType": {
												Type: "object",
											},
											"lastModifiedOn": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"tags": {
										Type:     "object",
										Nullable: true,
									},
								},
							},
							"hasData": {
								Type: "boolean",
							},
							"id": {
								Type: "object",
								Properties: map[string]*core.BodySchema{
									"location": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"displayName": {
												Type:     "string",
												Nullable: true,
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"name": {
										Type:     "string",
										Nullable: true,
									},
									"provider": {
										Type:     "string",
										Nullable: true,
									},
									"resourceGroupName": {
										Type:     "string",
										Nullable: true,
									},
									"resourceType": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"namespace": {
												Type:     "string",
												Nullable: true,
											},
											"type": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"subscriptionId": {
										Type:     "string",
										Nullable: true,
									},
								},
							},
							"url": {
								Type: "string",
							},
						},
					},
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	"GET /cdn/status/{resourceGroupName}/{deploymentName}": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"id": {
					Type:     "string",
					Nullable: true,
				},
				"name": {
					Type:     "string",
					Nullable: true,
				},
				"properties": {
					Type: "object",
					Properties: map[string]*core.BodySchema{
						"provisioningState": {
							Type:     "string",
							Nullable: true,
						},
						"timestamp": {
							Type: "string",
						},
					},
				},
				"type": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
	},
	"GET /cdn/{resourceGroupName}": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"data": {
					Nullable: true,
				},
				"url": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	// NOTE: recursive $ref #/components/schemas/ResourceIdentifier at GET /security/ddos response 200.resources[].data.id.parent left permissive
	// NOTE: recursive $ref #/components/schemas/ResourceIdentifier at GET /security/ddos response 200.resources[].id.parent left permissive
	"GET /security/ddos": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"resources": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"data": {
								Type: "object",
								Properties: map[string]*core.BodySchema{
									"id": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"location": {
												Type: "object",
												Properties: map[string]*core.BodySchema{
													"displayName": {
														Type:     "string",
														Nullable: true,
													},
													"name": {
														Type:     "string",
														Nullable: true,
													},
												},
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
											"provider": {
												Type:     "string",
												Nullable: true,
											},
											"resourceGroupName": {
												Type:     "string",
												Nullable: true,
											},
											"resourceType": {
												Type: "object",
												Properties: map[string]*core.BodySchema{
													"namespace": {
														Type:     "string",
														Nullable: true,
													},
													"type": {
														Type:     "string",
														Nullable: true,
													},
												},
											},
											"subscriptionId": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"location": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"displayName": {
												Type:     "string",
												Nullable: true,
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"managedBy": {
										Type:     "string",
										Nullable: true,
									},
									"name": {
										Type:     "string",
										Nullable: true,
									},
									"resourceGroupProvisioningState": {
										Type:     "string",
										Nullable: true,
									},
									"resourceType": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"namespace": {
												Type:     "string",
												Nullable: true,
											},
											"type": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"systemData": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"createdBy": {
												Type:     "string",
												Nullable: true,
											},
											"createdByType": {
												Type: "object",
											},
											"createdOn": {
												Type:     "string",
												Nullable: true,
											},
											"lastModifiedBy": {
												Type:     "string",
												Nullable: true,
											},
											"lastModifiedByType": {
												Type: "object",
											},
											"lastModifiedOn": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"tags": {
										Type:     "object",
										Nullable: true,
									},
								},
							},
							"hasData": {
								Type: "boolean",
							},
							"id": {
								Type: "object",
								Properties: map[string]*core.BodySchema{
									"location": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"displayName": {
												Type:     "string",
												Nullable: true,
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"name": {
										Type:     "string",
										Nullable: true,
									},
									"provider": {
										Type:     "string",
										Nullable: true,
									},
									"resourceGroupName": {
										Type:     "string",
										Nullable: true,
									},
									"resourceType": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"namespace": {
												Type:     "string",
												Nullable: true,
											},
											"type": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"subscriptionId": {
										Type:     "string",
										Nullable: true,
									},
								},
							},
							"url": {
								Type: "string",
							},
						},
					},
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	"GET /security/ddos/status/{resourceGroupName}/{deploymentName}": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"id": {
					Type:     "string",
					Nullable: true,
				},
				"name": {
					Type:     "string",
					Nullable: true,
				},
				"properties": {
					Type: "object",
					Properties: map[string]*core.BodySchema{
						"provisioningState": {
							Type:     "string",
							Nullable: true,
						},
						"timestamp": {
							Type: "string",
						},
					},
				},
				"type": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
	},
	"GET /security/ddos/{resourceGroupName}": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"data": {
					Nullable: true,
				},
				"url": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	// NOTE: recursive $ref #/components/schemas/ResourceIdentifier at GET /security/vulnerability response 200.resources[].data.id.parent left permissive
	// NOTE: recursive $ref #/components/schemas/ResourceIdentifier at GET /security/vulnerability response 200.resources[].id.parent left permissive
	"GET /security/vulnerability": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"resources": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"data": {
								Type: "object",
								Properties: map[string]*core.BodySchema{
									"id": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"location": {
												Type: "object",
												Properties: map[string]*core.BodySchema{
													"displayName": {
														Type:     "string",
														Nullable: true,
													},
													"name": {
														Type:     "string",
														Nullable: true,
													},
												},
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
											"provider": {
												Type:     "string",
												Nullable: true,
											},
											"resourceGroupName": {
												Type:     "string",
												Nullable: true,
											},
											"resourceType": {
												Type: "object",
												Properties: map[string]*core.BodySchema{
													"namespace": {
														Type:     "string",
														Nullable: true,
													},
													"type": {
														Type:     "string",
														Nullable: true,
													},
												},
											},
											"subscriptionId": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"location": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"displayName": {
												Type:     "string",
												Nullable: true,
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"managedBy": {
										Type:     "string",
										Nullable: true,
									},
									"name": {
										Type:     "string",
										Nullable: true,
									},
									"resourceGroupProvisioningState": {
										Type:     "string",
										Nullable: true,
									},
									"resourceType": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"namespace": {
												Type:     "string",
												Nullable: true,
											},
											"type": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"systemData": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"createdBy": {
												Type:     "string",
												Nullable: true,
											},
											"createdByType": {
												Type: "object",
											},
											"createdOn": {
												Type:     "string",
												Nullable: true,
											},
											"lastModifiedBy": {
												Type:     "string",
												Nullable: true,
											},
											"lastModifiedByType": {
												Type: "object",
											},
											"lastModifiedOn": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"tags": {
										Type:     "object",
										Nullable: true,
									},
								},
							},
							"hasData": {
								Type: "boolean",
							},
							"id": {
								Type: "object",
								Properties: map[string]*core.BodySchema{
									"location": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"displayName": {
												Type:     "string",
												Nullable: true,
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"name": {
										Type:     "string",
										Nullable: true,
									},
									"provider": {
										Type:     "string",
										Nullable: true,
									},
									"resourceGroupName": {
										Type:     "string",
										Nullable: true,
									},
									"resourceType": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"namespace": {
												Type:     "string",
												Nullable: true,
											},
											"type": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"subscriptionId": {
										Type:     "string",
										Nullable: true,
									},
								},
							},
							"url": {
								Type: "string",
							},
						},
					},
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	"GET /security/vulnerability/{resourceGroupName}": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"data": {
					Nullable: true,
				},
				"url": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	// NOTE: recursive $ref #/components/schemas/ResourceIdentifier at GET /security/waf response 200.resources[].data.id.parent left permissive
	// NOTE: recursive $ref #/components/schemas/ResourceIdentifier at GET /security/waf response 200.resources[].id.parent left permissive
	"GET /security/waf": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"resources": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"data": {
								Type: "object",
								Properties: map[string]*core.BodySchema{
									"id": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"location": {
												Type: "object",
												Properties: map[string]*core.BodySchema{
													"displayName": {
														Type:     "string",
														Nullable: true,
													},
													"name": {
														Type:     "string",
														Nullable: true,
													},
												},
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
											"provider": {
												Type:     "string",
												Nullable: true,
											},
											"resourceGroupName": {
												Type:     "string",
												Nullable: true,
											},
											"resourceType": {
												Type: "object",
												Properties: map[string]*core.BodySchema{
													"namespace": {
														Type:     "string",
														Nullable: true,
													},
													"type": {
														Type:     "string",
														Nullable: true,
													},
												},
											},
											"subscriptionId": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"location": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"displayName": {
												Type:     "string",
												Nullable: true,
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"managedBy": {
										Type:     "string",
										Nullable: true,
									},
									"name": {
										Type:     "string",
										Nullable: true,
									},
									"resourceGroupProvisioningState": {
										Type:     "string",
										Nullable: true,
									},
									"resourceType": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"namespace": {
												Type:     "string",
												Nullable: true,
											},
											"type": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"systemData": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"createdBy": {
												Type:     "string",
												Nullable: true,
											},
											"createdByType": {
												Type: "object",
											},
											"createdOn": {
												Type:     "string",
												Nullable: true,
											},
											"lastModifiedBy": {
												Type:     "string",
												Nullable: true,
											},
											"lastModifiedByType": {
												Type: "object",
											},
											"lastModifiedOn": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"tags": {
										Type:     "object",
										Nullable: true,
									},
								},
							},
							"hasData": {
								Type: "boolean",
							},
							"id": {
								Type: "object",
								Properties: map[string]*core.BodySchema{
									"location": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"displayName": {
												Type:     "string",
												Nullable: true,
											},
											"name": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"name": {
										Type:     "string",
										Nullable: true,
									},
									"provider": {
										Type:     "string",
										Nullable: true,
									},
									"resourceGroupName": {
										Type:     "string",
										Nullable: true,
									},
									"resourceType": {
										Type: "object",
										Properties: map[string]*core.BodySchema{
											"namespace": {
												Type:     "string",
												Nullable: true,
											},
											"type": {
												Type:     "string",
												Nullable: true,
											},
										},
									},
									"subscriptionId": {
										Type:     "string",
										Nullable: true,
									},
								},
							},
							"url": {
								Type: "string",
							},
						},
					},
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	"GET /security/waf/status/{resourceGroupName}/{deploymentName}": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"id": {
					Type:     "string",
					Nullable: true,
				},
				"name": {
					Type:     "string",
					Nullable: true,
				},
				"properties": {
					Type: "object",
					Properties: map[string]*core.BodySchema{
						"provisioningState": {
							Type:     "string",
							Nullable: true,
						},
						"timestamp": {
							Type: "string",
						},
					},
				},
				"type": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
	},
	"GET /security/waf/{resourceGroupName}": {
		200: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"data": {
					Nullable: true,
				},
				"url": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
		404: nil,
	},
	"POST /ai": {
		202: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"deploymentName": {
					Type:     "string",
					Nullable: true,
				},
				"resourceGroupName": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
	},
	"POST /analytics/datalake": {
		202: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"deploymentName": {
					Type:     "string",
					Nullable: true,
				},
				"resourceGroupName": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
	},
	"POST /analytics/dwh": {
		202: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"deploymentName": {
					Type:     "string",
					Nullable: true,
				},
				"resourceGroupName": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
	},
	"POST /analytics/etl": {
		202: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"deploymentName": {
					Type:     "string",
					Nullable: true,
				},
				"resourceGroupName": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
	},
	"POST /analytics/query": {
		202: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"deploymentName": {
					Type:     "string",
					Nullable: true,
				},
				"resourceGroupName": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
	},
	"POST /analytics/search": {
		202: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"deploymentName": {
					Type:     "string",
					Nullable: true,
				},
				"resourceGroupName": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
	},
	"POST /analytics/streaming": {
		202: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"deploymentName": {
					Type:     "string",
					Nullable: true,
				},
				"resourceGroupName": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
	},
	"POST /cdn": {
		202: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"deploymentName": {
					Type:     "string",
					Nullable: true,
				},
				"resourceGroupName": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
	},
	"POST /security/ddos": {
		202: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"deploymentName": {
					Type:     "string",
					Nullable: true,
				},
				"resourceGroupName": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
	},
	"POST /security/vulnerability": {
		202: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"installScript": {
					Type:     "string",
					Nullable: true,
				},
				"resourceGroupName": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
	},
	"POST /security/waf": {
		202: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"deploymentName": {
					Type:     "string",
					Nullable: true,
				},
				"resourceGroupName": {
					Type:     "string",
					Nullable: true,
				},
			},
		},
		400: {
			Type: "object",
			Properties: map[string]*core.BodySchema{
				"errors": {
					Type:     "array",
					Nullable: true,
					Items: &core.BodySchema{
						Type: "object",
						Properties: map[string]*core.BodySchema{
							"code": {
								Type:     "string",
								Nullable: true,
							},
							"message": {
								Type:     "string",
								Nullable: true,
							},
						},
					},
				},
			},
		},
	},
}
