// Code generated by internal/genvalidate from openapi/openapi.json; DO NOT EDIT.

package kms

import "github.com/sacloud/sakumock/core"

// bodySchemas maps "METHOD /path" (the mux pattern registered in the route
// table) to the request-body constraints declared in the OpenAPI spec.
// Entries for spec paths the mock does not serve are inert: the
// core.BodyValidator lookup simply never hits them.
var bodySchemas = map[string]*core.BodySchema{
	"POST /kms/keys": {
		Type:     "object",
		Required: []string{"Key"},
		Properties: map[string]*core.BodySchema{
			"Key": {
				Type:     "object",
				Required: []string{"Name"},
				Properties: map[string]*core.BodySchema{
					"Description": {
						Type: "string",
					},
					"Name": {
						Type:      "string",
						MinLength: new(1),
						MaxLength: new(255),
					},
					"PlainKey": {
						Type:      "string",
						MinLength: new(1),
					},
					"Tags": {
						Type:     "array",
						Nullable: true,
						Items: &core.BodySchema{
							Type:      "string",
							MinLength: new(1),
						},
					},
				},
			},
		},
	},
	"POST /kms/keys/{resource_id}/decrypt": {
		Type:     "object",
		Required: []string{"Key"},
		Properties: map[string]*core.BodySchema{
			"Key": {
				Type:     "object",
				Required: []string{"Cipher"},
				Properties: map[string]*core.BodySchema{
					"Cipher": {
						Type:      "string",
						MinLength: new(1),
						MaxLength: new(3072),
					},
				},
			},
		},
	},
	"POST /kms/keys/{resource_id}/encrypt": {
		Type:     "object",
		Required: []string{"Key"},
		Properties: map[string]*core.BodySchema{
			"Key": {
				Type:     "object",
				Required: []string{"Plain"},
				Properties: map[string]*core.BodySchema{
					"Algo": {
						Type: "string",
						Enum: []any{"aes-256-gcm", "aes-256-cbc", "aes-256-kw"},
					},
					"Plain": {
						Type: "string",
					},
				},
			},
		},
	},
	"POST /kms/keys/{resource_id}/schedule-destruction": {
		Type:     "object",
		Required: []string{"Key"},
		Properties: map[string]*core.BodySchema{
			"Key": {
				Type: "object",
				Properties: map[string]*core.BodySchema{
					"PendingDays": {
						Type:    "integer",
						Minimum: new(7.0),
						Maximum: new(90.0),
					},
				},
			},
		},
	},
	"POST /kms/keys/{resource_id}/status": {
		Type:     "object",
		Required: []string{"Key"},
		Properties: map[string]*core.BodySchema{
			"Key": {
				Type:     "object",
				Required: []string{"Status"},
				Properties: map[string]*core.BodySchema{
					"Status": {
						Type: "string",
						Enum: []any{"active", "restricted", "suspended"},
					},
				},
			},
		},
	},
	"PUT /kms/keys/{resource_id}": {
		Type:     "object",
		Required: []string{"Key"},
		Properties: map[string]*core.BodySchema{
			"Key": {
				Type:     "object",
				Required: []string{"Name"},
				Properties: map[string]*core.BodySchema{
					"Description": {
						Type: "string",
					},
					"Name": {
						Type:      "string",
						MinLength: new(1),
						MaxLength: new(255),
					},
					"Tags": {
						Type:     "array",
						Nullable: true,
						Items: &core.BodySchema{
							Type:      "string",
							MinLength: new(1),
						},
					},
				},
			},
		},
	},
}

// responseSchemas maps "METHOD /path" to the response constraints the
// OpenAPI spec declares, keyed by status code. A nil schema means the
// status is declared but its body carries no checkable constraints; a
// status absent from a route's map is not declared in the spec at all.
var responseSchemas = map[string]map[int]*core.BodySchema{
	"DELETE /kms/keys/{resource_id}": {
		204: nil,
	},
	"GET /kms/keys": {
		200: {
			Type:     "object",
			Required: []string{"Count", "From", "Keys", "Total", "is_ok"},
			Properties: map[string]*core.BodySchema{
				"Count": {
					Type: "integer",
				},
				"From": {
					Type: "integer",
				},
				"Keys": {
					Type: "array",
					Items: &core.BodySchema{
						Type:     "object",
						Required: []string{"CreatedAt", "Description", "ID", "KeyOrigin", "LatestVersion", "ModifiedAt", "Name", "ServiceClass", "Status", "Tags"},
						Properties: map[string]*core.BodySchema{
							"CreatedAt": {
								Type: "string",
							},
							"DeletionScheduledAfter": {
								Type:     "string",
								Nullable: true,
							},
							"Description": {
								Type: "string",
							},
							"ID": {
								Type: "string",
							},
							"KeyOrigin": {
								Type: "string",
								Enum: []any{"generated", "imported"},
							},
							"LatestVersion": {
								Type: "integer",
							},
							"ModifiedAt": {
								Type: "string",
							},
							"Name": {
								Type:      "string",
								MaxLength: new(255),
							},
							"ServiceClass": {
								Type: "string",
								Enum: []any{"cloud/kms/key", "cloud/kms/key/legacy"},
							},
							"Status": {
								Type: "string",
								Enum: []any{"active", "restricted", "suspended", "pending_destruction", "destroyed"},
							},
							"Tags": {
								Type:     "array",
								Nullable: true,
								Items: &core.BodySchema{
									Type:      "string",
									MinLength: new(1),
								},
							},
						},
					},
				},
				"Total": {
					Type: "integer",
				},
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
	"GET /kms/keys/{resource_id}": {
		200: {
			Type:     "object",
			Required: []string{"Key", "is_ok"},
			Properties: map[string]*core.BodySchema{
				"Key": {
					Type:     "object",
					Required: []string{"CreatedAt", "Description", "ID", "KeyOrigin", "LatestVersion", "ModifiedAt", "Name", "ServiceClass", "Status", "Tags"},
					Properties: map[string]*core.BodySchema{
						"CreatedAt": {
							Type: "string",
						},
						"DeletionScheduledAfter": {
							Type:     "string",
							Nullable: true,
						},
						"Description": {
							Type: "string",
						},
						"ID": {
							Type: "string",
						},
						"KeyOrigin": {
							Type: "string",
							Enum: []any{"generated", "imported"},
						},
						"LatestVersion": {
							Type: "integer",
						},
						"ModifiedAt": {
							Type: "string",
						},
						"Name": {
							Type:      "string",
							MaxLength: new(255),
						},
						"ServiceClass": {
							Type: "string",
							Enum: []any{"cloud/kms/key", "cloud/kms/key/legacy"},
						},
						"Status": {
							Type: "string",
							Enum: []any{"active", "restricted", "suspended", "pending_destruction", "destroyed"},
						},
						"Tags": {
							Type:     "array",
							Nullable: true,
							Items: &core.BodySchema{
								Type:      "string",
								MinLength: new(1),
							},
						},
					},
				},
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
	"POST /kms/keys": {
		201: {
			Type:     "object",
			Required: []string{"Key", "is_ok"},
			Properties: map[string]*core.BodySchema{
				"Key": {
					Type:     "object",
					Required: []string{"CreatedAt", "Description", "ID", "KeyOrigin", "LatestVersion", "ModifiedAt", "Name", "ServiceClass", "Status", "Tags"},
					Properties: map[string]*core.BodySchema{
						"CreatedAt": {
							Type: "string",
						},
						"DeletionScheduledAfter": {
							Type:     "string",
							Nullable: true,
						},
						"Description": {
							Type: "string",
						},
						"ID": {
							Type: "string",
						},
						"KeyOrigin": {
							Type: "string",
							Enum: []any{"generated", "imported"},
						},
						"LatestVersion": {
							Type: "integer",
						},
						"ModifiedAt": {
							Type: "string",
						},
						"Name": {
							Type:      "string",
							MaxLength: new(255),
						},
						"ServiceClass": {
							Type: "string",
							Enum: []any{"cloud/kms/key", "cloud/kms/key/legacy"},
						},
						"Status": {
							Type: "string",
							Enum: []any{"active", "restricted", "suspended", "pending_destruction", "destroyed"},
						},
						"Tags": {
							Type:     "array",
							Nullable: true,
							Items: &core.BodySchema{
								Type:      "string",
								MinLength: new(1),
							},
						},
					},
				},
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
	"POST /kms/keys/{resource_id}/decrypt": {
		200: {
			Type:     "object",
			Required: []string{"Key", "is_ok"},
			Properties: map[string]*core.BodySchema{
				"Key": {
					Type:     "object",
					Required: []string{"Plain"},
					Properties: map[string]*core.BodySchema{
						"Plain": {
							Type: "string",
						},
					},
				},
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
	"POST /kms/keys/{resource_id}/encrypt": {
		200: {
			Type:     "object",
			Required: []string{"Key", "is_ok"},
			Properties: map[string]*core.BodySchema{
				"Key": {
					Type:     "object",
					Required: []string{"Cipher"},
					Properties: map[string]*core.BodySchema{
						"Cipher": {
							Type: "string",
						},
					},
				},
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
	"POST /kms/keys/{resource_id}/rotate": {
		200: {
			Type:     "object",
			Required: []string{"Key", "is_ok"},
			Properties: map[string]*core.BodySchema{
				"Key": {
					Type:     "object",
					Required: []string{"CreatedAt", "Description", "ID", "KeyOrigin", "LatestVersion", "ModifiedAt", "Name", "ServiceClass", "Status", "Tags"},
					Properties: map[string]*core.BodySchema{
						"CreatedAt": {
							Type: "string",
						},
						"DeletionScheduledAfter": {
							Type:     "string",
							Nullable: true,
						},
						"Description": {
							Type: "string",
						},
						"ID": {
							Type: "string",
						},
						"KeyOrigin": {
							Type: "string",
							Enum: []any{"generated", "imported"},
						},
						"LatestVersion": {
							Type: "integer",
						},
						"ModifiedAt": {
							Type: "string",
						},
						"Name": {
							Type:      "string",
							MaxLength: new(255),
						},
						"ServiceClass": {
							Type: "string",
							Enum: []any{"cloud/kms/key", "cloud/kms/key/legacy"},
						},
						"Status": {
							Type: "string",
							Enum: []any{"active", "restricted", "suspended", "pending_destruction", "destroyed"},
						},
						"Tags": {
							Type:     "array",
							Nullable: true,
							Items: &core.BodySchema{
								Type:      "string",
								MinLength: new(1),
							},
						},
					},
				},
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
	"POST /kms/keys/{resource_id}/schedule-destruction": {
		200: {
			Type:     "object",
			Required: []string{"Key", "is_ok"},
			Properties: map[string]*core.BodySchema{
				"Key": {
					Type:     "object",
					Required: []string{"DeletionScheduledAfter", "Status"},
					Properties: map[string]*core.BodySchema{
						"DeletionScheduledAfter": {
							Type:     "string",
							Nullable: true,
						},
						"Status": {
							Type: "string",
							Enum: []any{"active", "restricted", "suspended", "pending_destruction", "destroyed"},
						},
					},
				},
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
	"POST /kms/keys/{resource_id}/status": {
		200: {
			Type:     "object",
			Required: []string{"Key", "is_ok"},
			Properties: map[string]*core.BodySchema{
				"Key": {
					Type:     "object",
					Required: []string{"Status"},
					Properties: map[string]*core.BodySchema{
						"Status": {
							Type: "string",
							Enum: []any{"active", "restricted", "suspended"},
						},
					},
				},
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
	"PUT /kms/keys/{resource_id}": {
		200: {
			Type:     "object",
			Required: []string{"Key", "is_ok"},
			Properties: map[string]*core.BodySchema{
				"Key": {
					Type:     "object",
					Required: []string{"CreatedAt", "Description", "ID", "KeyOrigin", "LatestVersion", "ModifiedAt", "Name", "ServiceClass", "Status", "Tags"},
					Properties: map[string]*core.BodySchema{
						"CreatedAt": {
							Type: "string",
						},
						"DeletionScheduledAfter": {
							Type:     "string",
							Nullable: true,
						},
						"Description": {
							Type: "string",
						},
						"ID": {
							Type: "string",
						},
						"KeyOrigin": {
							Type: "string",
							Enum: []any{"generated", "imported"},
						},
						"LatestVersion": {
							Type: "integer",
						},
						"ModifiedAt": {
							Type: "string",
						},
						"Name": {
							Type:      "string",
							MaxLength: new(255),
						},
						"ServiceClass": {
							Type: "string",
							Enum: []any{"cloud/kms/key", "cloud/kms/key/legacy"},
						},
						"Status": {
							Type: "string",
							Enum: []any{"active", "restricted", "suspended", "pending_destruction", "destroyed"},
						},
						"Tags": {
							Type:     "array",
							Nullable: true,
							Items: &core.BodySchema{
								Type:      "string",
								MinLength: new(1),
							},
						},
					},
				},
				"is_ok": {
					Type: "boolean",
				},
			},
		},
	},
}
