// Code generated by internal/genvalidate from openapi/openapi.json; DO NOT EDIT.

package kms

import "github.com/sacloud/sakumock/core"

// bodySchemas maps "METHOD /path" (the mux pattern registered in the route
// table) to the request-body constraints declared in the OpenAPI spec.
// Entries for spec paths the mock does not serve are inert: the
// core.BodyValidator lookup simply never hits them.
var bodySchemas = map[string]*core.BodySchema{
	"POST /kms/keys": {
		Type:     "object",
		Required: []string{"Key"},
		Properties: map[string]*core.BodySchema{
			"Key": {
				Type:     "object",
				Required: []string{"Name"},
				Properties: map[string]*core.BodySchema{
					"CreatedAt": {
						Type: "string",
					},
					"Description": {
						Type: "string",
					},
					"ID": {
						Type: "string",
					},
					"KeyOrigin": {
						Type: "string",
						Enum: []any{"generated", "imported"},
					},
					"ModifiedAt": {
						Type: "string",
					},
					"Name": {
						Type:      "string",
						MaxLength: core.IntPtr(255),
					},
					"PlainKey": {
						Type: "string",
					},
					"Tags": {
						Type: "array",
						Items: &core.BodySchema{
							Type: "string",
						},
					},
				},
			},
		},
	},
	"POST /kms/keys/{resource_id}/decrypt": {
		Type:     "object",
		Required: []string{"Key"},
		Properties: map[string]*core.BodySchema{
			"Key": {
				Type:     "object",
				Required: []string{"Cipher"},
				Properties: map[string]*core.BodySchema{
					"Cipher": {
						Type: "string",
					},
				},
			},
		},
	},
	"POST /kms/keys/{resource_id}/encrypt": {
		Type:     "object",
		Required: []string{"Key"},
		Properties: map[string]*core.BodySchema{
			"Key": {
				Type:     "object",
				Required: []string{"Plain"},
				Properties: map[string]*core.BodySchema{
					"Algo": {
						Type: "string",
						Enum: []any{"aes-256-gcm", "aes-256-cbc", "aes-256-kw"},
					},
					"Plain": {
						Type: "string",
					},
				},
			},
		},
	},
	"POST /kms/keys/{resource_id}/schedule-destruction": {
		Type:     "object",
		Required: []string{"Key"},
		Properties: map[string]*core.BodySchema{
			"Key": {
				Type:     "object",
				Required: []string{"PendingDays"},
				Properties: map[string]*core.BodySchema{
					"PendingDays": {
						Type: "integer",
					},
				},
			},
		},
	},
	"POST /kms/keys/{resource_id}/status": {
		Type:     "object",
		Required: []string{"Key"},
		Properties: map[string]*core.BodySchema{
			"Key": {
				Type: "object",
				Properties: map[string]*core.BodySchema{
					"Status": {
						Type: "string",
						Enum: []any{"active", "restricted", "suspended"},
					},
				},
			},
		},
	},
	"PUT /kms/keys/{resource_id}": {
		Type:     "object",
		Required: []string{"Key"},
		Properties: map[string]*core.BodySchema{
			"Key": {
				Type:     "object",
				Required: []string{"Description", "Name", "Tags"},
				Properties: map[string]*core.BodySchema{
					"CreatedAt": {
						Type: "string",
					},
					"Description": {
						Type: "string",
					},
					"ID": {
						Type: "string",
					},
					"KeyOrigin": {
						Type: "string",
						Enum: []any{"generated", "imported"},
					},
					"LatestVersion": {
						Type: "integer",
					},
					"ModifiedAt": {
						Type: "string",
					},
					"Name": {
						Type:      "string",
						MaxLength: core.IntPtr(255),
					},
					"ServiceClass": {
						Type: "string",
						Enum: []any{"cloud/kms/key", "cloud/kms/key/legacy"},
					},
					"Status": {
						Type: "string",
						Enum: []any{"active", "restricted", "suspended", "pending_destruction"},
					},
					"Tags": {
						Type: "array",
						Items: &core.BodySchema{
							Type: "string",
						},
					},
				},
			},
		},
	},
}
