// Code generated by internal/genvalidate from openapi/openapi.json; DO NOT EDIT.

package objectstorage

import "github.com/sacloud/sakumock/core"

// bodySchemas maps "METHOD /path" (the mux pattern registered in the route
// table) to the request-body constraints declared in the OpenAPI spec.
// Entries for spec paths the mock does not serve are inert: the
// core.BodyValidator lookup simply never hits them.
var bodySchemas = map[string]*core.BodySchema{
	"POST /fed/v1/buckets/{name}/replication": {
		Type:     "object",
		Required: []string{"dest_bucket"},
		Properties: map[string]*core.BodySchema{
			"dest_bucket": {
				Type: "string",
			},
		},
	},
	"POST /{site}/v2/permissions": {
		Type: "object",
		Properties: map[string]*core.BodySchema{
			"bucket_controls": {
				Type: "array",
				Items: &core.BodySchema{
					Type: "object",
					Properties: map[string]*core.BodySchema{
						"bucket_name": {
							Type:    "string",
							Pattern: "^[a-zA-Z][a-zA-Z0-9\\-]{2,}",
						},
						"can_read": {
							Type: "boolean",
						},
						"can_write": {
							Type: "boolean",
						},
						"created_at": {
							Type: "string",
						},
					},
				},
			},
			"display_name": {
				Type:    "string",
				Pattern: "^.+$",
			},
		},
	},
	"PUT /fed/v1/buckets/{name}": {
		Type:     "object",
		Required: []string{"cluster_id"},
		Properties: map[string]*core.BodySchema{
			"cluster_id": {
				Type: "string",
			},
			"plan": {
				Type:     "object",
				Nullable: true,
				Properties: map[string]*core.BodySchema{
					"service_class_path": {
						Type: "string",
					},
					"type": {
						Type: "string",
						Enum: []any{"standard", "archive"},
					},
				},
			},
		},
	},
	"PUT /{site}/v2/buckets/{name}/encryption": {
		Type:     "object",
		Required: []string{"kms_key_id"},
		Properties: map[string]*core.BodySchema{
			"kms_key_id": {
				Type:    "string",
				Pattern: "\\d{1,12}",
			},
		},
	},
	"PUT /{site}/v2/buckets/{name}/plan": {
		Type:     "object",
		Required: []string{"new_plan", "previous_contract"},
		Properties: map[string]*core.BodySchema{
			"new_plan": {
				Type:     "object",
				Required: []string{"service_class_path", "type"},
				Properties: map[string]*core.BodySchema{
					"service_class_path": {
						Type: "string",
					},
					"type": {
						Type: "string",
						Enum: []any{"standard", "archive"},
					},
				},
			},
			"previous_contract": {
				Type: "object",
				Properties: map[string]*core.BodySchema{
					"resource_id": {
						Type:    "string",
						Pattern: "\\d{1,12}",
					},
				},
			},
		},
	},
	"PUT /{site}/v2/permissions/{id}": {
		Type: "object",
		Properties: map[string]*core.BodySchema{
			"bucket_controls": {
				Type: "array",
				Items: &core.BodySchema{
					Type: "object",
					Properties: map[string]*core.BodySchema{
						"bucket_name": {
							Type:    "string",
							Pattern: "^[a-zA-Z][a-zA-Z0-9\\-]{2,}",
						},
						"can_read": {
							Type: "boolean",
						},
						"can_write": {
							Type: "boolean",
						},
						"created_at": {
							Type: "string",
						},
					},
				},
			},
			"display_name": {
				Type:    "string",
				Pattern: "^.+$",
			},
		},
	},
}
