// Code generated by internal/genvalidate from openapi/openapi.json; DO NOT EDIT.

package apprundedicated

import "github.com/sacloud/sakumock/core"

// bodySchemas maps "METHOD /path" (the mux pattern registered in the route
// table) to the request-body constraints declared in the OpenAPI spec.
// Entries for spec paths the mock does not serve are inert: the
// core.BodyValidator lookup simply never hits them.
var bodySchemas = map[string]*core.BodySchema{
	"POST /applications": {
		Type:     "object",
		Required: []string{"clusterID", "name"},
		Properties: map[string]*core.BodySchema{
			"clusterID": {
				Type: "string",
			},
			"name": {
				Type:      "string",
				MinLength: core.IntPtr(1),
				MaxLength: core.IntPtr(20),
				Pattern:   "^[a-zA-Z0-9_-]+$",
			},
		},
	},
	"POST /applications/{applicationID}/versions": {
		Type:     "object",
		Required: []string{"cpu", "env", "exposedPorts", "image", "memory", "registryPassword", "registryPasswordAction", "registryUsername", "scalingMode"},
		Properties: map[string]*core.BodySchema{
			"cmd": {
				Type: "array",
				Items: &core.BodySchema{
					Type: "string",
				},
				MaxItems: core.IntPtr(20),
			},
			"cpu": {
				Type:    "integer",
				Minimum: core.Float64Ptr(100),
				Maximum: core.Float64Ptr(64000),
			},
			"env": {
				Type: "array",
				Items: &core.BodySchema{
					Type:     "object",
					Required: []string{"key", "secret"},
					Properties: map[string]*core.BodySchema{
						"key": {
							Type:      "string",
							MinLength: core.IntPtr(1),
							MaxLength: core.IntPtr(255),
						},
						"secret": {
							Type: "boolean",
						},
						"value": {
							Type:      "string",
							MaxLength: core.IntPtr(4096),
						},
					},
				},
				MaxItems: core.IntPtr(50),
			},
			"exposedPorts": {
				Type: "array",
				Items: &core.BodySchema{
					Type:     "object",
					Required: []string{"healthCheck", "loadBalancerPort", "targetPort", "useLetsEncrypt"},
					Properties: map[string]*core.BodySchema{
						"healthCheck": {
							Type:     "object",
							Nullable: true,
							Required: []string{"intervalSeconds", "path", "timeoutSeconds"},
							Properties: map[string]*core.BodySchema{
								"intervalSeconds": {
									Type:    "integer",
									Minimum: core.Float64Ptr(3),
									Maximum: core.Float64Ptr(60),
								},
								"path": {
									Type:      "string",
									MaxLength: core.IntPtr(200),
								},
								"timeoutSeconds": {
									Type:    "integer",
									Maximum: core.Float64Ptr(60),
								},
							},
						},
						"host": {
							Type: "array",
							Items: &core.BodySchema{
								Type: "string",
							},
							MaxItems: core.IntPtr(5),
						},
						"loadBalancerPort": {
							Type:     "integer",
							Nullable: true,
							Minimum:  core.Float64Ptr(1),
							Maximum:  core.Float64Ptr(65535),
						},
						"targetPort": {
							Type:    "integer",
							Minimum: core.Float64Ptr(1),
							Maximum: core.Float64Ptr(65535),
						},
						"useLetsEncrypt": {
							Type: "boolean",
						},
					},
				},
				MaxItems: core.IntPtr(5),
			},
			"fixedScale": {
				Type:    "integer",
				Minimum: core.Float64Ptr(1),
				Maximum: core.Float64Ptr(50),
			},
			"image": {
				Type:      "string",
				MaxLength: core.IntPtr(512),
			},
			"maxScale": {
				Type:    "integer",
				Minimum: core.Float64Ptr(1),
				Maximum: core.Float64Ptr(50),
			},
			"memory": {
				Type:    "integer",
				Minimum: core.Float64Ptr(128),
				Maximum: core.Float64Ptr(131072),
			},
			"minScale": {
				Type:    "integer",
				Minimum: core.Float64Ptr(1),
				Maximum: core.Float64Ptr(50),
			},
			"registryPassword": {
				Type:      "string",
				Nullable:  true,
				MaxLength: core.IntPtr(255),
			},
			"registryPasswordAction": {
				Type: "string",
				Enum: []any{"keep", "remove", "new"},
			},
			"registryUsername": {
				Type:      "string",
				Nullable:  true,
				MaxLength: core.IntPtr(255),
			},
			"scaleInThreshold": {
				Type:    "integer",
				Minimum: core.Float64Ptr(30),
				Maximum: core.Float64Ptr(70),
			},
			"scaleOutThreshold": {
				Type:    "integer",
				Minimum: core.Float64Ptr(50),
				Maximum: core.Float64Ptr(99),
			},
			"scalingMode": {
				Type: "string",
				Enum: []any{"manual", "cpu"},
			},
		},
	},
	"POST /clusters": {
		Type:     "object",
		Required: []string{"name", "ports", "servicePrincipalID"},
		Properties: map[string]*core.BodySchema{
			"letsEncryptEmail": {
				Type:    "string",
				Pattern: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$",
			},
			"name": {
				Type:      "string",
				MinLength: core.IntPtr(1),
				MaxLength: core.IntPtr(20),
				Pattern:   "^[a-zA-Z0-9_-]+$",
			},
			"ports": {
				Type: "array",
				Items: &core.BodySchema{
					Type:     "object",
					Required: []string{"port", "protocol"},
					Properties: map[string]*core.BodySchema{
						"port": {
							Type:    "integer",
							Minimum: core.Float64Ptr(1),
							Maximum: core.Float64Ptr(65535),
						},
						"protocol": {
							Type: "string",
							Enum: []any{"http", "https", "tcp"},
						},
					},
				},
				MaxItems: core.IntPtr(5),
			},
			"servicePrincipalID": {
				Type:      "string",
				MinLength: core.IntPtr(12),
				MaxLength: core.IntPtr(12),
			},
		},
	},
	"POST /clusters/{clusterID}/asg": {
		Type:     "object",
		Required: []string{"interfaces", "maxNodes", "minNodes", "name", "workerServiceClassPath", "zone"},
		Properties: map[string]*core.BodySchema{
			"interfaces": {
				Type: "array",
				Items: &core.BodySchema{
					Type:     "object",
					Required: []string{"connectsToLB", "interfaceIndex", "upstream"},
					Properties: map[string]*core.BodySchema{
						"connectsToLB": {
							Type: "boolean",
						},
						"defaultGateway": {
							Type: "string",
						},
						"interfaceIndex": {
							Type: "integer",
						},
						"ipPool": {
							Type: "array",
							Items: &core.BodySchema{
								Type:     "object",
								Required: []string{"end", "start"},
								Properties: map[string]*core.BodySchema{
									"end": {
										Type:    "string",
										Pattern: "^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}$",
									},
									"start": {
										Type:    "string",
										Pattern: "^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}$",
									},
								},
							},
							MaxItems: core.IntPtr(20),
						},
						"netmaskLen": {
							Type:    "integer",
							Minimum: core.Float64Ptr(8),
							Maximum: core.Float64Ptr(29),
						},
						"packetFilterID": {
							Type: "string",
						},
						"upstream": {
							Type: "string",
						},
					},
				},
				MinItems: core.IntPtr(1),
				MaxItems: core.IntPtr(5),
			},
			"maxNodes": {
				Type:    "integer",
				Minimum: core.Float64Ptr(1),
				Maximum: core.Float64Ptr(10),
			},
			"minNodes": {
				Type:    "integer",
				Minimum: core.Float64Ptr(1),
				Maximum: core.Float64Ptr(10),
			},
			"name": {
				Type:      "string",
				MinLength: core.IntPtr(1),
				MaxLength: core.IntPtr(20),
				Pattern:   "^[a-zA-Z0-9_-]+$",
			},
			"nameServers": {
				Type: "array",
				Items: &core.BodySchema{
					Type:    "string",
					Pattern: "^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}$",
				},
				MinItems: core.IntPtr(1),
				MaxItems: core.IntPtr(3),
			},
			"workerServiceClassPath": {
				Type:      "string",
				MinLength: core.IntPtr(1),
				MaxLength: core.IntPtr(255),
			},
			"zone": {
				Type: "string",
			},
		},
	},
	"POST /clusters/{clusterID}/asg/{autoScalingGroupID}/load_balancers": {
		Type:     "object",
		Required: []string{"interfaces", "name", "serviceClassPath"},
		Properties: map[string]*core.BodySchema{
			"interfaces": {
				Type: "array",
				Items: &core.BodySchema{
					Type:     "object",
					Required: []string{"interfaceIndex", "upstream"},
					Properties: map[string]*core.BodySchema{
						"defaultGateway": {
							Type: "string",
						},
						"interfaceIndex": {
							Type: "integer",
						},
						"ipPool": {
							Type: "array",
							Items: &core.BodySchema{
								Type:     "object",
								Required: []string{"end", "start"},
								Properties: map[string]*core.BodySchema{
									"end": {
										Type:    "string",
										Pattern: "^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}$",
									},
									"start": {
										Type:    "string",
										Pattern: "^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}$",
									},
								},
							},
							MaxItems: core.IntPtr(20),
						},
						"netmaskLen": {
							Type:    "integer",
							Minimum: core.Float64Ptr(8),
							Maximum: core.Float64Ptr(29),
						},
						"packetFilterID": {
							Type: "string",
						},
						"upstream": {
							Type: "string",
						},
						"vip": {
							Type:    "string",
							Pattern: "^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}$",
						},
						"virtualRouterID": {
							Type: "integer",
						},
					},
				},
				MinItems: core.IntPtr(1),
				MaxItems: core.IntPtr(5),
			},
			"name": {
				Type:      "string",
				MinLength: core.IntPtr(1),
				MaxLength: core.IntPtr(20),
				Pattern:   "^[a-zA-Z0-9_-]+$",
			},
			"nameServers": {
				Type: "array",
				Items: &core.BodySchema{
					Type:    "string",
					Pattern: "^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}$",
				},
				MinItems: core.IntPtr(1),
				MaxItems: core.IntPtr(3),
			},
			"serviceClassPath": {
				Type:      "string",
				MinLength: core.IntPtr(1),
				MaxLength: core.IntPtr(255),
			},
		},
	},
	"POST /clusters/{clusterID}/certificates": {
		Type:     "object",
		Required: []string{"certificatePem", "name", "privatekeyPem"},
		Properties: map[string]*core.BodySchema{
			"certificatePem": {
				Type:      "string",
				MaxLength: core.IntPtr(1000000),
			},
			"intermediateCertificatePem": {
				Type:      "string",
				MaxLength: core.IntPtr(1000000),
			},
			"name": {
				Type:      "string",
				MinLength: core.IntPtr(1),
				MaxLength: core.IntPtr(20),
				Pattern:   "^[a-zA-Z0-9_.-]+$",
			},
			"privatekeyPem": {
				Type:      "string",
				MaxLength: core.IntPtr(1000000),
			},
		},
	},
	"PUT /applications/{applicationID}": {
		Type:     "object",
		Required: []string{"activeVersion"},
		Properties: map[string]*core.BodySchema{
			"activeVersion": {
				Type:     "integer",
				Nullable: true,
			},
		},
	},
	"PUT /clusters/{clusterID}": {
		Type:     "object",
		Required: []string{"servicePrincipalID"},
		Properties: map[string]*core.BodySchema{
			"letsEncryptEmail": {
				Type:    "string",
				Pattern: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$",
			},
			"servicePrincipalID": {
				Type: "string",
			},
		},
	},
	"PUT /clusters/{clusterID}/asg/{autoScalingGroupID}/worker_nodes/{workerNodeID}/draining": {
		Type:     "object",
		Required: []string{"draining"},
		Properties: map[string]*core.BodySchema{
			"draining": {
				Type: "boolean",
			},
		},
	},
	"PUT /clusters/{clusterID}/certificates/{certificateID}": {
		Type:     "object",
		Required: []string{"certificatePem", "name", "privatekeyPem"},
		Properties: map[string]*core.BodySchema{
			"certificatePem": {
				Type:      "string",
				MaxLength: core.IntPtr(1000000),
			},
			"intermediateCertificatePem": {
				Type:      "string",
				MaxLength: core.IntPtr(1000000),
			},
			"name": {
				Type:      "string",
				MinLength: core.IntPtr(1),
				MaxLength: core.IntPtr(20),
				Pattern:   "^[a-zA-Z0-9_.-]+$",
			},
			"privatekeyPem": {
				Type:      "string",
				MaxLength: core.IntPtr(1000000),
			},
		},
	},
}
